In [3]:
import serpapi
from dotenv import load_dotenv
import pandas as pd
import os

load_dotenv()
SERPAPI_API_KEY = os.getenv('SERPAPI_API_KEY')
client = serpapi.Client(api_key=SERPAPI_API_KEY)

In [ ]:
def scrape_google_jobs(query):
    search_params = {
        "engine": "google_jobs",
        "q": query,
        "hl": "en",
        "location": "Singapore",
        "api_key": SERPAPI_API_KEY
    }

    results = serpapi.search(**search_params)
    print(results)

    jobs_results = results["jobs_results"]
    jobs_results_df = pd.DataFrame(jobs_results)
    return jobs_results_df

preferred_role = 'AI Engineer'
results = scrape_google_jobs(query=preferred_role)

{
    "search_metadata": {
        "id": "69515365bca7e53381302c91",
        "status": "Success",
        "json_endpoint": "https://serpapi.com/searches/256b043477b7d259/69515365bca7e53381302c91.json",
        "created_at": "2025-12-28 15:57:25 UTC",
        "processed_at": "2025-12-28 15:57:25 UTC",
        "google_jobs_url": "https://www.google.com/search?q=AI+Engineer&uule=w+CAIQICIJU2luZ2Fwb3Jl&hl=en&udm=8",
        "raw_html_file": "https://serpapi.com/searches/256b043477b7d259/69515365bca7e53381302c91.html",
        "total_time_taken": 2.81
    },
    "search_parameters": {
        "q": "AI Engineer",
        "engine": "google_jobs",
        "location_requested": "Singapore",
        "location_used": "Singapore",
        "google_domain": "google.com",
        "hl": "en"
    },
    "filters": [
        {
            "name": "No degree",
            "parameters": {
                "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKz7UQRvnII2foAfYX6aj3QevF8vnddNMeuC--HuT4_sjvUIA_ljOMumFWaMh7L4dlojOtNCXxIRovUaPdxqA_HlU-ykDkk7kVmEV_tmwJFTleGs32gAMGDi_L13sXOZrh8rYh2xUBsYWCbStuqX8LBDHXKAso",
                "q": "AI Engineer no degree"
            },
            "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+no+degree&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz7UQRvnII2foAfYX6aj3QevF8vnddNMeuC--HuT4_sjvUIA_ljOMumFWaMh7L4dlojOtNCXxIRovUaPdxqA_HlU-ykDkk7kVmEV_tmwJFTleGs32gAMGDi_L13sXOZrh8rYh2xUBsYWCbStuqX8LBDHXKAso&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QxKsJKAB6BAgUEAE&ictx=0",
            "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+no+degree&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz7UQRvnII2foAfYX6aj3QevF8vnddNMeuC--HuT4_sjvUIA_ljOMumFWaMh7L4dlojOtNCXxIRovUaPdxqA_HlU-ykDkk7kVmEV_tmwJFTleGs32gAMGDi_L13sXOZrh8rYh2xUBsYWCbStuqX8LBDHXKAso"
        },
        {
            "name": "Remote",
            "parameters": {
                "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzzx1qfahp2UWthC9jUZ8uQVNJ8VjhXKk6XocduzP7LkfcQ4HXyZcUBlF-RHMiv5lei8WOwOdBu0m4oYb4MCSgcdMmACoJuIRf8FCKD3GOjo41-6bGZPTGKQUsc4cX3wHSOiUs2FM3_ZF6_m1R8avQalq-9ow",
                "q": "AI Engineer remote"
            },
            "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+remote&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzzx1qfahp2UWthC9jUZ8uQVNJ8VjhXKk6XocduzP7LkfcQ4HXyZcUBlF-RHMiv5lei8WOwOdBu0m4oYb4MCSgcdMmACoJuIRf8FCKD3GOjo41-6bGZPTGKQUsc4cX3wHSOiUs2FM3_ZF6_m1R8avQalq-9ow&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QxKsJKAF6BAgTEAE&ictx=0",
            "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+remote&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzzx1qfahp2UWthC9jUZ8uQVNJ8VjhXKk6XocduzP7LkfcQ4HXyZcUBlF-RHMiv5lei8WOwOdBu0m4oYb4MCSgcdMmACoJuIRf8FCKD3GOjo41-6bGZPTGKQUsc4cX3wHSOiUs2FM3_ZF6_m1R8avQalq-9ow"
        },
        {
            "name": "No degree",
            "parameters": {
                "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKz7UQRvnII2foAfYX6aj3QevF8vnddNMeuC--HuT4_sjvUIA_ljOMumFWaMh7L4dlojOtNCXxIRovUaPdxqA_HlU-ykDkk7kVmEV_tmwJFTleGs32gAMGDi_L13sXOZrh8rYh2xUBsYWCbStuqX8LBDHXKAso",
                "q": "AI Engineer no degree"
            },
            "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+no+degree&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz7UQRvnII2foAfYX6aj3QevF8vnddNMeuC--HuT4_sjvUIA_ljOMumFWaMh7L4dlojOtNCXxIRovUaPdxqA_HlU-ykDkk7kVmEV_tmwJFTleGs32gAMGDi_L13sXOZrh8rYh2xUBsYWCbStuqX8LBDHXKAso&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QxKsJKAJ6BAgYEAE&ictx=0",
            "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+no+degree&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz7UQRvnII2foAfYX6aj3QevF8vnddNMeuC--HuT4_sjvUIA_ljOMumFWaMh7L4dlojOtNCXxIRovUaPdxqA_HlU-ykDkk7kVmEV_tmwJFTleGs32gAMGDi_L13sXOZrh8rYh2xUBsYWCbStuqX8LBDHXKAso"
        },
        {
            "name": "Remote",
            "parameters": {
                "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzzx1qfahp2UWthC9jUZ8uQVNJ8VjhXKk6XocduzP7LkfcQ4HXyZcUBlF-RHMiv5lei8WOwOdBu0m4oYb4MCSgcdMmACoJuIRf8FCKD3GOjo41-6bGZPTGKQUsc4cX3wHSOiUs2FM3_ZF6_m1R8avQalq-9ow",
                "q": "AI Engineer remote"
            },
            "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+remote&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzzx1qfahp2UWthC9jUZ8uQVNJ8VjhXKk6XocduzP7LkfcQ4HXyZcUBlF-RHMiv5lei8WOwOdBu0m4oYb4MCSgcdMmACoJuIRf8FCKD3GOjo41-6bGZPTGKQUsc4cX3wHSOiUs2FM3_ZF6_m1R8avQalq-9ow&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QxKsJKAN6BAgXEAE&ictx=0",
            "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+remote&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzzx1qfahp2UWthC9jUZ8uQVNJ8VjhXKk6XocduzP7LkfcQ4HXyZcUBlF-RHMiv5lei8WOwOdBu0m4oYb4MCSgcdMmACoJuIRf8FCKD3GOjo41-6bGZPTGKQUsc4cX3wHSOiUs2FM3_ZF6_m1R8avQalq-9ow"
        },
        {
            "name": "Date posted",
            "options": [
                {
                    "name": "Yesterday",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzczNOmafPZjUJ-10sPQ8SkvnMkjyfxImbvnajv7vCl5V9yw0jRpNktWIgrVqWGcO2CSdhEOHRXZy0OHKQKKZnPseIaqOYAKEfsWHZJApeDxgg-wa0jXMdT1GEx6HYOJnLERghEvUVvFkd88gdrsvL15ufsSvxFAj5Wq5Ua6ky_X5ZBJ08yd4hfQ1HWMP-Tc7nLGXAzVrIAVviCcX-oj3UGldMnr5NApQF4gNtsYZw8Hl0SG6jkH5k6j7a-bJdKQIcyBQh_odTa_v-jh86pzb6dwWy1gB8WM79xQQETdLN8doODoTafK1z7zotd-CSMXyQt6YMSQlu7ADs6dGc_e6vyokCKeE",
                        "q": "AI Engineer since yesterday"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+since+yesterday&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzczNOmafPZjUJ-10sPQ8SkvnMkjyfxImbvnajv7vCl5V9yw0jRpNktWIgrVqWGcO2CSdhEOHRXZy0OHKQKKZnPseIaqOYAKEfsWHZJApeDxgg-wa0jXMdT1GEx6HYOJnLERghEvUVvFkd88gdrsvL15ufsSvxFAj5Wq5Ua6ky_X5ZBJ08yd4hfQ1HWMP-Tc7nLGXAzVrIAVviCcX-oj3UGldMnr5NApQF4gNtsYZw8Hl0SG6jkH5k6j7a-bJdKQIcyBQh_odTa_v-jh86pzb6dwWy1gB8WM79xQQETdLN8doODoTafK1z7zotd-CSMXyQt6YMSQlu7ADs6dGc_e6vyokCKeE&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAC",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+since+yesterday&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzczNOmafPZjUJ-10sPQ8SkvnMkjyfxImbvnajv7vCl5V9yw0jRpNktWIgrVqWGcO2CSdhEOHRXZy0OHKQKKZnPseIaqOYAKEfsWHZJApeDxgg-wa0jXMdT1GEx6HYOJnLERghEvUVvFkd88gdrsvL15ufsSvxFAj5Wq5Ua6ky_X5ZBJ08yd4hfQ1HWMP-Tc7nLGXAzVrIAVviCcX-oj3UGldMnr5NApQF4gNtsYZw8Hl0SG6jkH5k6j7a-bJdKQIcyBQh_odTa_v-jh86pzb6dwWy1gB8WM79xQQETdLN8doODoTafK1z7zotd-CSMXyQt6YMSQlu7ADs6dGc_e6vyokCKeE"
                },
                {
                    "name": "Last 3 days",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzOa08CK1HbEnjTk7D-hOWHdB4NijXKGphshJHl_yl4BH_2Z6wP1bBIWcndqFPOrfWacOrE9WrHuRa_bSjDLt2c5lDAh5mTtJerY0lhaq7k2btCmZPnOw4-Nx0k3JAhLKOdyCzsBHkhoSLg_KpuX2eL_5vFIbbgBKjoasJTiIOEQagorSARAOtkvrag84COxupPQZ2Uf6s879d0V5jcqq4aYHTMvdqLZCoIwklZxWaPlTspb-ybAvBsVKKhoYHC5lJza-KZZhhcBQrU1O_XKgabqcJwRDfhkpx_vFaLXmCAf1roHZIw6xEHXHYwDK9ow7_yvt7k6PMzJqIrQLIYibCnocpsXc",
                        "q": "AI Engineer in the last 3 days"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+in+the+last+3+days&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzOa08CK1HbEnjTk7D-hOWHdB4NijXKGphshJHl_yl4BH_2Z6wP1bBIWcndqFPOrfWacOrE9WrHuRa_bSjDLt2c5lDAh5mTtJerY0lhaq7k2btCmZPnOw4-Nx0k3JAhLKOdyCzsBHkhoSLg_KpuX2eL_5vFIbbgBKjoasJTiIOEQagorSARAOtkvrag84COxupPQZ2Uf6s879d0V5jcqq4aYHTMvdqLZCoIwklZxWaPlTspb-ybAvBsVKKhoYHC5lJza-KZZhhcBQrU1O_XKgabqcJwRDfhkpx_vFaLXmCAf1roHZIw6xEHXHYwDK9ow7_yvt7k6PMzJqIrQLIYibCnocpsXc&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAD",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+in+the+last+3+days&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzOa08CK1HbEnjTk7D-hOWHdB4NijXKGphshJHl_yl4BH_2Z6wP1bBIWcndqFPOrfWacOrE9WrHuRa_bSjDLt2c5lDAh5mTtJerY0lhaq7k2btCmZPnOw4-Nx0k3JAhLKOdyCzsBHkhoSLg_KpuX2eL_5vFIbbgBKjoasJTiIOEQagorSARAOtkvrag84COxupPQZ2Uf6s879d0V5jcqq4aYHTMvdqLZCoIwklZxWaPlTspb-ybAvBsVKKhoYHC5lJza-KZZhhcBQrU1O_XKgabqcJwRDfhkpx_vFaLXmCAf1roHZIw6xEHXHYwDK9ow7_yvt7k6PMzJqIrQLIYibCnocpsXc"
                },
                {
                    "name": "Last week",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKz6TiOanbvUNTjEtbtwht5GpuL26Cyn1hl7YsncTcgnXzUAXycHWhDRuQLQjbplny7-IWQ5pU56uhwOrOJEGnckggWt8F7wofgmUUQAa8o6xtHBllamhHJG47QxMchV8iN17foF4veQ3wR7rju9LGRFT9EkWueUGc1DaK-XSIjUsSrCkmwDZb1rj_K59K_zxLZi97JalcjgI2ViV5PNkk8zdr0bPMPD-ooTmkaN7xI8wwo4lEda5L-RVIW1Mjv-7vPe3gjfxa4g1SNqofqrROV-JajmFOsuL9XlMtbsE85_1dbzQNhQYdG6MKJF8-WXm6Ndt3BIKKQSQ2jz3E347sb0iUwRyY",
                        "q": "AI Engineer in the last week"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+in+the+last+week&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz6TiOanbvUNTjEtbtwht5GpuL26Cyn1hl7YsncTcgnXzUAXycHWhDRuQLQjbplny7-IWQ5pU56uhwOrOJEGnckggWt8F7wofgmUUQAa8o6xtHBllamhHJG47QxMchV8iN17foF4veQ3wR7rju9LGRFT9EkWueUGc1DaK-XSIjUsSrCkmwDZb1rj_K59K_zxLZi97JalcjgI2ViV5PNkk8zdr0bPMPD-ooTmkaN7xI8wwo4lEda5L-RVIW1Mjv-7vPe3gjfxa4g1SNqofqrROV-JajmFOsuL9XlMtbsE85_1dbzQNhQYdG6MKJF8-WXm6Ndt3BIKKQSQ2jz3E347sb0iUwRyY&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAE",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+in+the+last+week&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz6TiOanbvUNTjEtbtwht5GpuL26Cyn1hl7YsncTcgnXzUAXycHWhDRuQLQjbplny7-IWQ5pU56uhwOrOJEGnckggWt8F7wofgmUUQAa8o6xtHBllamhHJG47QxMchV8iN17foF4veQ3wR7rju9LGRFT9EkWueUGc1DaK-XSIjUsSrCkmwDZb1rj_K59K_zxLZi97JalcjgI2ViV5PNkk8zdr0bPMPD-ooTmkaN7xI8wwo4lEda5L-RVIW1Mjv-7vPe3gjfxa4g1SNqofqrROV-JajmFOsuL9XlMtbsE85_1dbzQNhQYdG6MKJF8-WXm6Ndt3BIKKQSQ2jz3E347sb0iUwRyY"
                },
                {
                    "name": "Last month",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzBey0OS2SV5gKtWxz4dQ51vOwkFLi4KzUMHyUJdHfr81fDlNGxfemdbj1esAtoE8WxODmmkTqePOuj4369_-ZaMskvdVR6G7jWZfonC1TJIL-jXgdf7QCl06hKC04uzZgS423sMxobnljRhDwI8kag3ZSnu9i2BTfVS4ZYinVZSMMTi3_zp2afwkKV3wSoXzw9Sf0LxnsrKDDaF69adbZA5ctIm1uPxi-E8uYdg4g3vIeRQJwdRl5XwVUIFEUbOClSOqanFRhCr3BrS333ZmoWnlrYrXpedsMjRuWsYN4w7JO9bh2H9-C8-AENmYKmhDrxgS2nAoyd5dTdihxbR7lg_zyR5g",
                        "q": "AI Engineer in the last month"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+in+the+last+month&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzBey0OS2SV5gKtWxz4dQ51vOwkFLi4KzUMHyUJdHfr81fDlNGxfemdbj1esAtoE8WxODmmkTqePOuj4369_-ZaMskvdVR6G7jWZfonC1TJIL-jXgdf7QCl06hKC04uzZgS423sMxobnljRhDwI8kag3ZSnu9i2BTfVS4ZYinVZSMMTi3_zp2afwkKV3wSoXzw9Sf0LxnsrKDDaF69adbZA5ctIm1uPxi-E8uYdg4g3vIeRQJwdRl5XwVUIFEUbOClSOqanFRhCr3BrS333ZmoWnlrYrXpedsMjRuWsYN4w7JO9bh2H9-C8-AENmYKmhDrxgS2nAoyd5dTdihxbR7lg_zyR5g&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAF",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+in+the+last+month&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzBey0OS2SV5gKtWxz4dQ51vOwkFLi4KzUMHyUJdHfr81fDlNGxfemdbj1esAtoE8WxODmmkTqePOuj4369_-ZaMskvdVR6G7jWZfonC1TJIL-jXgdf7QCl06hKC04uzZgS423sMxobnljRhDwI8kag3ZSnu9i2BTfVS4ZYinVZSMMTi3_zp2afwkKV3wSoXzw9Sf0LxnsrKDDaF69adbZA5ctIm1uPxi-E8uYdg4g3vIeRQJwdRl5XwVUIFEUbOClSOqanFRhCr3BrS333ZmoWnlrYrXpedsMjRuWsYN4w7JO9bh2H9-C8-AENmYKmhDrxgS2nAoyd5dTdihxbR7lg_zyR5g"
                }
            ]
        },
        {
            "name": "Date posted",
            "options": [
                {
                    "name": "Yesterday",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzczNOmafPZjUJ-10sPQ8SkvnMkjyfxImbvnajv7vCl5V9yw0jRpNktWIgrVqWGcO2CSdhEOHRXZy0OHKQKKZnPseIaqOYAKEfsWHZJApeDxgg-wa0jXMdT1GEx6HYOJnLERghEvUVvFkd88gdrsvL15ufsSvxFAj5Wq5Ua6ky_X5ZBJ08yd4hfQ1HWMP-Tc7nLGXAzVrIAVviCcX-oj3UGldMnr5NApQF4gNtsYZw8Hl0SG6jkH5k6j7a-bJdKQIcyBQh_odTa_v-jh86pzb6dwWy1gB8WM79xQQETdLN8doODoTafK1z7zotd-CSMXyQt6YMSQlu7ADs6dGc_e6vyokCKeE",
                        "q": "AI Engineer since yesterday"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+since+yesterday&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzczNOmafPZjUJ-10sPQ8SkvnMkjyfxImbvnajv7vCl5V9yw0jRpNktWIgrVqWGcO2CSdhEOHRXZy0OHKQKKZnPseIaqOYAKEfsWHZJApeDxgg-wa0jXMdT1GEx6HYOJnLERghEvUVvFkd88gdrsvL15ufsSvxFAj5Wq5Ua6ky_X5ZBJ08yd4hfQ1HWMP-Tc7nLGXAzVrIAVviCcX-oj3UGldMnr5NApQF4gNtsYZw8Hl0SG6jkH5k6j7a-bJdKQIcyBQh_odTa_v-jh86pzb6dwWy1gB8WM79xQQETdLN8doODoTafK1z7zotd-CSMXyQt6YMSQlu7ADs6dGc_e6vyokCKeE&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAC",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+since+yesterday&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzczNOmafPZjUJ-10sPQ8SkvnMkjyfxImbvnajv7vCl5V9yw0jRpNktWIgrVqWGcO2CSdhEOHRXZy0OHKQKKZnPseIaqOYAKEfsWHZJApeDxgg-wa0jXMdT1GEx6HYOJnLERghEvUVvFkd88gdrsvL15ufsSvxFAj5Wq5Ua6ky_X5ZBJ08yd4hfQ1HWMP-Tc7nLGXAzVrIAVviCcX-oj3UGldMnr5NApQF4gNtsYZw8Hl0SG6jkH5k6j7a-bJdKQIcyBQh_odTa_v-jh86pzb6dwWy1gB8WM79xQQETdLN8doODoTafK1z7zotd-CSMXyQt6YMSQlu7ADs6dGc_e6vyokCKeE"
                },
                {
                    "name": "Last 3 days",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzOa08CK1HbEnjTk7D-hOWHdB4NijXKGphshJHl_yl4BH_2Z6wP1bBIWcndqFPOrfWacOrE9WrHuRa_bSjDLt2c5lDAh5mTtJerY0lhaq7k2btCmZPnOw4-Nx0k3JAhLKOdyCzsBHkhoSLg_KpuX2eL_5vFIbbgBKjoasJTiIOEQagorSARAOtkvrag84COxupPQZ2Uf6s879d0V5jcqq4aYHTMvdqLZCoIwklZxWaPlTspb-ybAvBsVKKhoYHC5lJza-KZZhhcBQrU1O_XKgabqcJwRDfhkpx_vFaLXmCAf1roHZIw6xEHXHYwDK9ow7_yvt7k6PMzJqIrQLIYibCnocpsXc",
                        "q": "AI Engineer in the last 3 days"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+in+the+last+3+days&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzOa08CK1HbEnjTk7D-hOWHdB4NijXKGphshJHl_yl4BH_2Z6wP1bBIWcndqFPOrfWacOrE9WrHuRa_bSjDLt2c5lDAh5mTtJerY0lhaq7k2btCmZPnOw4-Nx0k3JAhLKOdyCzsBHkhoSLg_KpuX2eL_5vFIbbgBKjoasJTiIOEQagorSARAOtkvrag84COxupPQZ2Uf6s879d0V5jcqq4aYHTMvdqLZCoIwklZxWaPlTspb-ybAvBsVKKhoYHC5lJza-KZZhhcBQrU1O_XKgabqcJwRDfhkpx_vFaLXmCAf1roHZIw6xEHXHYwDK9ow7_yvt7k6PMzJqIrQLIYibCnocpsXc&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAD",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+in+the+last+3+days&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzOa08CK1HbEnjTk7D-hOWHdB4NijXKGphshJHl_yl4BH_2Z6wP1bBIWcndqFPOrfWacOrE9WrHuRa_bSjDLt2c5lDAh5mTtJerY0lhaq7k2btCmZPnOw4-Nx0k3JAhLKOdyCzsBHkhoSLg_KpuX2eL_5vFIbbgBKjoasJTiIOEQagorSARAOtkvrag84COxupPQZ2Uf6s879d0V5jcqq4aYHTMvdqLZCoIwklZxWaPlTspb-ybAvBsVKKhoYHC5lJza-KZZhhcBQrU1O_XKgabqcJwRDfhkpx_vFaLXmCAf1roHZIw6xEHXHYwDK9ow7_yvt7k6PMzJqIrQLIYibCnocpsXc"
                },
                {
                    "name": "Last week",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKz6TiOanbvUNTjEtbtwht5GpuL26Cyn1hl7YsncTcgnXzUAXycHWhDRuQLQjbplny7-IWQ5pU56uhwOrOJEGnckggWt8F7wofgmUUQAa8o6xtHBllamhHJG47QxMchV8iN17foF4veQ3wR7rju9LGRFT9EkWueUGc1DaK-XSIjUsSrCkmwDZb1rj_K59K_zxLZi97JalcjgI2ViV5PNkk8zdr0bPMPD-ooTmkaN7xI8wwo4lEda5L-RVIW1Mjv-7vPe3gjfxa4g1SNqofqrROV-JajmFOsuL9XlMtbsE85_1dbzQNhQYdG6MKJF8-WXm6Ndt3BIKKQSQ2jz3E347sb0iUwRyY",
                        "q": "AI Engineer in the last week"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+in+the+last+week&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz6TiOanbvUNTjEtbtwht5GpuL26Cyn1hl7YsncTcgnXzUAXycHWhDRuQLQjbplny7-IWQ5pU56uhwOrOJEGnckggWt8F7wofgmUUQAa8o6xtHBllamhHJG47QxMchV8iN17foF4veQ3wR7rju9LGRFT9EkWueUGc1DaK-XSIjUsSrCkmwDZb1rj_K59K_zxLZi97JalcjgI2ViV5PNkk8zdr0bPMPD-ooTmkaN7xI8wwo4lEda5L-RVIW1Mjv-7vPe3gjfxa4g1SNqofqrROV-JajmFOsuL9XlMtbsE85_1dbzQNhQYdG6MKJF8-WXm6Ndt3BIKKQSQ2jz3E347sb0iUwRyY&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAE",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+in+the+last+week&uds=AOm0WdE2fekQnsyfYEw8JPYozOKz6TiOanbvUNTjEtbtwht5GpuL26Cyn1hl7YsncTcgnXzUAXycHWhDRuQLQjbplny7-IWQ5pU56uhwOrOJEGnckggWt8F7wofgmUUQAa8o6xtHBllamhHJG47QxMchV8iN17foF4veQ3wR7rju9LGRFT9EkWueUGc1DaK-XSIjUsSrCkmwDZb1rj_K59K_zxLZi97JalcjgI2ViV5PNkk8zdr0bPMPD-ooTmkaN7xI8wwo4lEda5L-RVIW1Mjv-7vPe3gjfxa4g1SNqofqrROV-JajmFOsuL9XlMtbsE85_1dbzQNhQYdG6MKJF8-WXm6Ndt3BIKKQSQ2jz3E347sb0iUwRyY"
                },
                {
                    "name": "Last month",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzBey0OS2SV5gKtWxz4dQ51vOwkFLi4KzUMHyUJdHfr81fDlNGxfemdbj1esAtoE8WxODmmkTqePOuj4369_-ZaMskvdVR6G7jWZfonC1TJIL-jXgdf7QCl06hKC04uzZgS423sMxobnljRhDwI8kag3ZSnu9i2BTfVS4ZYinVZSMMTi3_zp2afwkKV3wSoXzw9Sf0LxnsrKDDaF69adbZA5ctIm1uPxi-E8uYdg4g3vIeRQJwdRl5XwVUIFEUbOClSOqanFRhCr3BrS333ZmoWnlrYrXpedsMjRuWsYN4w7JO9bh2H9-C8-AENmYKmhDrxgS2nAoyd5dTdihxbR7lg_zyR5g",
                        "q": "AI Engineer in the last month"
                    },
                    "link": "https://www.google.com/search?sca_esv=72195fbabfad6857&hl=en&q=AI+Engineer+in+the+last+month&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzBey0OS2SV5gKtWxz4dQ51vOwkFLi4KzUMHyUJdHfr81fDlNGxfemdbj1esAtoE8WxODmmkTqePOuj4369_-ZaMskvdVR6G7jWZfonC1TJIL-jXgdf7QCl06hKC04uzZgS423sMxobnljRhDwI8kag3ZSnu9i2BTfVS4ZYinVZSMMTi3_zp2afwkKV3wSoXzw9Sf0LxnsrKDDaF69adbZA5ctIm1uPxi-E8uYdg4g3vIeRQJwdRl5XwVUIFEUbOClSOqanFRhCr3BrS333ZmoWnlrYrXpedsMjRuWsYN4w7JO9bh2H9-C8-AENmYKmhDrxgS2nAoyd5dTdihxbR7lg_zyR5g&udm=8&sa=X&ved=2ahUKEwjMwIr30uCRAxUOmmoFHc0kFS4QkbEKegQIFhAF",
                    "serpapi_link": "https://serpapi.com/search.json?engine=google_jobs&google_domain=google.com&hl=en&location=Singapore&q=AI+Engineer+in+the+last+month&uds=AOm0WdE2fekQnsyfYEw8JPYozOKzBey0OS2SV5gKtWxz4dQ51vOwkFLi4KzUMHyUJdHfr81fDlNGxfemdbj1esAtoE8WxODmmkTqePOuj4369_-ZaMskvdVR6G7jWZfonC1TJIL-jXgdf7QCl06hKC04uzZgS423sMxobnljRhDwI8kag3ZSnu9i2BTfVS4ZYinVZSMMTi3_zp2afwkKV3wSoXzw9Sf0LxnsrKDDaF69adbZA5ctIm1uPxi-E8uYdg4g3vIeRQJwdRl5XwVUIFEUbOClSOqanFRhCr3BrS333ZmoWnlrYrXpedsMjRuWsYN4w7JO9bh2H9-C8-AENmYKmhDrxgS2nAoyd5dTdihxbR7lg_zyR5g"
                }
            ]
        },
        {
            "name": "Job type",
            "options": [
                {
                    "name": "Full time",
                    "parameters": {
                        "uds": "AOm0WdE2fekQnsyfYEw8JPYozOKzg_3jT9FbCRXy-UfxcNRznmKFBeP0KAWSfQQAH4sJppxoWTdsqjMFOhT4qChA0HNgeRU8tseVT4lxa8Pwnh_eI0ZQg8BGGzIHN0vW-HN72EImzs2Hx-fkuNmICJqXtdzqeqto1zkkicvUQ9ulOPpLC_oSOZIv9rCwWd1MEF-6AIwdg3J7HQaf5gV5Ei4Oab4T6I0Hj0yj1usmQyMEg9tt8F07PDL27v64RtR7cWGW4kSXWQFh-tg6sSSoFjdHS5KZ1-xVO862DQ_Szsb8e-eNFC9vwFEMaFgm3moDi3z6JaGYSe8xKGc698yGD9dxZvhWPagRpQ",
                        "q": "AI Engineer full time"
                    },

In [7]:
results

,title,company_name,location,via,share_link,extensions,detected_extensions,description,apply_options,job_id,thumbnail
0,AI Engineer,HEINEKEN,Singapore,HEINEKEN Careers - The HEINEKEN Company,https://www.google.com/search?ibp=htl;jobs&q=A...,"[5 days ago, Full-time]","{'posted_at': '5 days ago', 'schedule_type': '...",The AI Engineer will be a key contributor to H...,[{'title': 'HEINEKEN Careers - The HEINEKEN Co...,eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlciIsImNvbXBhbn...,NaN
1,(Senior) AI Engineer - BCG X Singapore,Boston Consulting Group,Singapore,Boston Consulting Group,https://www.google.com/search?ibp=htl;jobs&q=A...,[Full-time],{'schedule_type': 'Full-time'},Who We Are\n\nBoston Consulting Group partners...,"[{'title': 'Boston Consulting Group', 'link': ...",eyJqb2JfdGl0bGUiOiIoU2VuaW9yKSBBSSBFbmdpbmVlci...,https://serpapi.com/searches/69515365bca7e5338...
2,AI Engineer,Zoom,Singapore,Zoom Careers,https://www.google.com/search?ibp=htl;jobs&q=A...,"[16 days ago, Full-time]","{'posted_at': '16 days ago', 'schedule_type': ...","What you can expect\n\nAs an AI Engineer, you ...","[{'title': 'Zoom Careers', 'link': 'https://ca...",eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlciIsImNvbXBhbn...,NaN
3,Artificial Intelligence Engineer (Azure OpenAI...,Avensys Consulting,Singapore,LinkedIn Singapore,https://www.google.com/search?ibp=htl;jobs&q=A...,"[3 days ago, Contractor]","{'posted_at': '3 days ago', 'schedule_type': '...",Avensys is a reputed global IT professional se...,"[{'title': 'LinkedIn Singapore', 'link': 'http...",eyJqb2JfdGl0bGUiOiJBcnRpZmljaWFsIEludGVsbGlnZW...,https://serpapi.com/searches/69515365bca7e5338...
4,Junior AI Engineers (Associates/Senior Associa...,EY,Singapore,EY Careers,https://www.google.com/search?ibp=htl;jobs&q=A...,[Full-time],{'schedule_type': 'Full-time'},"At EY, we develop you with future-focused skil...","[{'title': 'EY Careers', 'link': 'https://care...",eyJqb2JfdGl0bGUiOiJKdW5pb3IgQUkgRW5naW5lZXJzIC...,https://serpapi.com/searches/69515365bca7e5338...
5,"Associate, AI Engineer (Singapore)","Nomura Holdings, inc.",Singapore,Careers I NOMURA,https://www.google.com/search?ibp=htl;jobs&q=A...,[Full-time],{'schedule_type': 'Full-time'},Job Title: AI Engineer\n\nCorporate Title: Ass...,"[{'title': 'Careers I NOMURA', 'link': 'https:...",eyJqb2JfdGl0bGUiOiJBc3NvY2lhdGUsIEFJIEVuZ2luZW...,NaN
6,"AI Engineer, Artificial Intelligence, GEC",ST Engineering Group,Singapore,ST Engineering,https://www.google.com/search?ibp=htl;jobs&q=A...,"[14 days ago, Full-time]","{'posted_at': '14 days ago', 'schedule_type': ...",The Company - ST Engineering Group Engineering...,"[{'title': 'ST Engineering', 'link': 'https://...",eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlciwgQXJ0aWZpY2...,NaN
7,Solutions Engineer - Cloud & AI,Cisco,Singapore,Cisco Careers,https://www.google.com/search?ibp=htl;jobs&q=A...,"[11 days ago, Full-time, No degree mentioned]","{'posted_at': '11 days ago', 'schedule_type': ...","Your Impact\n\nAs a Solutions Engineer, you wi...","[{'title': 'Cisco Careers', 'link': 'https://c...",eyJqb2JfdGl0bGUiOiJTb2x1dGlvbnMgRW5naW5lZXIgLS...,https://serpapi.com/searches/69515365bca7e5338...
8,"AI Engineer, Digital Energy",Schneider Electric,Singapore,Schneider Electric,https://www.google.com/search?ibp=htl;jobs&q=A...,"[20 days ago, Full-time]","{'posted_at': '20 days ago', 'schedule_type': ...",In Schneider Electric everything we do promote...,"[{'title': 'Schneider Electric', 'link': 'http...",eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlciwgRGlnaXRhbC...,NaN
9,Software Engineer 2 - AI Infra and Platform En...,Org_Subtype_BU022_Infrastructure_Solutions_Group,Singapore,Dell Careers - Dell Technologies,https://www.google.com/search?ibp=htl;jobs&q=A...,"[14 days ago, Full-time]","{'posted_at': '14 days ago', 'schedule_type': ...",AI Infra and Platform Software Engineer\n\nThe...,"[{'title': 'Dell Careers - Dell Technologies',...",eyJqb2JfdGl0bGUiOiJTb2Z0d2FyZSBFbmdpbmVlciAyIC...,NaN

In [ ]:
def scrape_google_jobs(query):
    search_params = {
        "engine": "google_jobs",
        "q": query,
        "hl": "en",
        "location": "Singapore",
        "api_key": SERPAPI_API_KEY
    }

    results = serpapi.search(**search_params)
    jobs_results = results["jobs_results"]

    next_page_tokens = 0
    while True:
        results = serpapi.search(**search_params)
        if 'job_results' not in results:
            print('No more job results. ❌')
            break
        next_page_tokens += 10
    jobs_results = results['jobs_results']
    return jobs_results

In [9]:
scrape_google_jobs('Data Scientist')

No more job results. ❌

[{'title': 'Staff Data Scientist (Relo to SF) | Singapore, SG',
  'company_name': 'Airwallex',
  'location': 'Singapore',
  'via': 'EFinancialCareers SG',
  'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Data+Scientist&htidocid=CzUUHss5JdrreE1YAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_0XNsQrCMBAAUFz7AQ5ON6poI4JLnQSx4mg-oFzDNY3EXMgd2MF_8VfFyeWtr_rMqqtVHAY4oyJYFyhpEIXlnSKDMtjLCt5gQ_KYudAGbAtbuHEPQljcCJygZfaRFsdRNUtjjEisvShqcLXjp-FEPU_mwb386GTEQjmiUrc_7KY6J7-en0J5YYw0QUj_7wtjvDPAogAAAA&shmds=v1_AdeF8KiU98N59-JhNU5tMtzLJYHdWS9-OT0F7aWerssBfAJB3Q&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Data+Scientist&htidocid=CzUUHss5JdrreE1YAAAAAA%3D%3D',
  'thumbnail': 'https://serpapi.com/searches/6951574866bc788cab4c662d/images/e994f1c370e0337ba5c045cedd0646a00d7e4a17a93c37de9737efd647eb1d40.jpeg',
  'extensions': ['1 day ago', 'Full-time'],
  'detected_extensions': {'posted_at': '1 day ago',
   'schedule_type': 'Full-time'},
  'description': 'Staff Data Scientist (Relo to SF)\n\nAbout Airwallex\n\nAirwallex is the only unified payments and financial platform for global businesses. Powered by our unique combination of proprietary infrastructure and software, we empower over 200,000 businesses worldwide - including Brex, Rippling, Navan, Qantas, SHEIN and many more - with fully integrated solutions to manage everything from business accounts, payments, spend management and treasury, to embedded finance at a global scale.\n\nProudly founded in Melbourne, we have a team of over 2,000 of the brightest and most innovative people in tech across 26 offices around the globe. Valued at US$8 billion and backed by world-leading investors including T. Rowe Price, Visa, Mastercard, Robinhood Ventures, Sequoia, Salesforce Ventures, DST Global, and Lone Pine Capital, Airwallex is leading the charge in building the global payments and financial platform of the future. If you\'re ready to do the most ambitious work of your career, join us.\n\nAttributes We Value\n\nWe hire successful builders with founder-like energy who want real impact, accelerated learning, and true ownership. You bring strong role-related expertise and sharp thinking, and you\'re motivated by our mission and operating principles. You move fast with good judgment, dig deep with curiosity, and make decisions from first principles, balancing speed and rigor.\n\nYou\'re humble and collaborative; turn zero-to-one ideas into real products, and you "get stuff done" end-to-end. You use AI to work smarter and solve problems faster. Here, you\'ll tackle complex, high-visibility problems with exceptional teammates and grow your career as we build the future of global banking. If that sounds like you, let\'s build what\'s next.\n\nAbout the team\n\nThe Strategic Data Science team team provides Airwallex\'s Leadership with the data, tooling, and insights needed to amplify Airwallex\'s rapid growth. We partner across the entire business, giving us an overarching view and opinion on what Airwallex should prioritize. Our expertise spans the full data stack, and we use it to tackle complex data problems that will shape the future of global fintech. The team is growing quickly, and currently based in the US, China, and Singapore.\n\nThis role is based in San Francisco.\n\nLearn more about the data science team in this blog\n\nWhat you\'ll do\n\nResponsibilities:\n\n• Be the go-to data partner for the CEO and Regional Business Leads.\n• Use causal inference methods to understand how macroeconomic events impact the business.\n• Leverage AI to generate insights and improve business and team efficiency.\n• Lead Airwallex\'s forecasting efforts by 1) building tools that aggregate and evaluate forecasts 2) applying advanced statistical methods to build your own forecasts.\n• Scope and build data products. In some cases building MVPs, and in others, fully fleshed out solutions.\n• Mentor junior team members and cultivate an environment grounded in technical excellence, clear communication, and proactive critical thinking.\nWho you are\n\nWe\'re looking for people who meet the minimum qualifications for this role. The preferred qualifications are great to have, but are not mandatory.\n\nMinimum qualifications:\n\n• 7+ years industry experience and an advanced degree (PhD or MS) in a quantitative field (e.g. Statistics, Engineering, Sciences, Computer Science, Economics)\n• Excellent communication skills, ideally with a proven track record of working directly with executive-level stakeholders to influence strategy.\n• Expertise in causal inference methods and forecasting.\n• Expertise in data querying languages (e.g. SQL) and scripting languages (e.g. Python, R).\n• Experience with data architecture technologies such as Airflow, Databricks, and dbt.\nPreferred qualifications:\n\n• Experience in technology, financial services and/or a high growth environment.\n• Experience with Excel and Finance systems (e.g. Oracle).\n#sanfrancisco\nApplicant Safety Policy: Fraud and Third-Party Recruiters\n\nTo protect you from recruitment scams, please be aware that Airwallex will not ask for bank details, sensitive ID numbers (i.e. passport), or any form of payment during the application or interview process. All official communication will come from an @airwallex.com email address. Please apply only through careers.airwallex.com or our official LinkedIn page.\n\nAirwallex does not accept unsolicited resumes from search firms/recruiters. Airwallex will not pay any fees to search firms/recruiters if a candidate is submitted by a search firm/recruiter unless an agreement has been entered into with respect to specific open position(s). Search firms/recruiters submitting resumes to Airwallex on an unsolicited basis shall be deemed to accept this condition, regardless of any other provision to the contrary.\n\nEqual opportunity\n\nAirwallex is proud to be an equal opportunity employer. We value diversity and anyone seeking employment at Airwallex is considered based on merit, qualifications, competence and talent. We don\'t regard color, religion, race, national origin, sexual orientation, ancestry, citizenship, sex, marital or family status, disability, gender, or any other legally protected status when making our hiring decisions. If you have a disability or special need that requires accommodation, please let us know.',
  'apply_options': [{'title': 'EFinancialCareers SG',
    'link': 'https://www.efinancialcareers.sg/jobs-Singapore-Singapore-Staff_Data_Scientist_Relo_to_SF.id23620563?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}],
  'job_id': 'eyJqb2JfdGl0bGUiOiJTdGFmZiBEYXRhIFNjaWVudGlzdCAoUmVsbyB0byBTRikgfCBTaW5nYXBvcmUsIFNHIiwiY29tcGFueV9uYW1lIjoiQWlyd2FsbGV4IiwiYWRkcmVzc19jaXR5IjoiU2luZ2Fwb3JlIiwiaHRpZG9jaWQiOiJDelVVSHNzNUpkcnJlRTFZQUFBQUFBPT0iLCJ1dWxlIjoidytDQUlRSUNJSlUybHVaMkZ3YjNKbCIsImhsIjoiZW4ifQ=='},
 {'title': 'Digital Health R&D – Data Scientist – Data Analytics and Statistics',
  'company_name': 'Lilly',
  'location': 'Singapore',
  'via': 'Lilly Careers - Eli Lilly',
  'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Data+Scientist&htidocid=XnXoZ9zfPqdvssrrAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_0WKMQoCMRBFsd3S0moqC8GNCDZaCQuKWLm9MhuHJBIzYWeK3c47eBKv5Ekklc2H996vPpPq2gQXFCMcCaN6uMwb-L7e0KAitDZQ0iD6V_uEcdRgBTDdoVUsueASTtyBEPbWAyc4MLtIs51XzbI1RiTWTsrf1pafhhN1PJgHd1LmJh57yhGVbuvNaqhzcovpOcQ4QkjQhuQwc08_mPJCmLQAAAA&shmds=v1_AdeF8Kh3T1_D-S304EgsrQsu5J48XnkLFp3oIrA6PYNluFy4kQ&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Data+Scientist&htidocid=XnXoZ9zfPqdvssrrAAAAAA%3D%3D',
  'thumbnail': 'https://serpapi.com/searches/6951574866bc788cab4c662d/images/e994f1c370e0337bd39237e5994b0fbf03b8a72e8c7e24282a9bf074b6b07d4c.png',
  'extensions': ['4 days ago', 'Full-time'],
  'detected_extensions': {'posted_at': '4 days ago',
   'schedule_type': 'Full-time'},
  'description': 'At Lilly, we unite caring with discovery to make life better for people around the world. We are a global healthcare leader headquartered in Indianapolis, Indiana. Our employees around the world work to discover and bring life-changing medicines to those who need them, improve the understanding and management of disease, and give back to our communities through philanthropy and volunteerism. We give our best effort to our work, and we put people first. We’re looking for people who are determined to make life better for people around the world.\n\nThe DH R&D Data Scientist Data Analytics and Statistics role closely partners with the broader DH R&D team (most notably Sensor Lab, Medical, and Clinical Operations), cross-functional scientists and colleagues, stakeholders and third-party providers to define, implement, and deliver digital measure outcomes primarily for non-LY exploratory DH R&D trials via a key role in the Digital Health Innovation Hub being established in Singapore at the Lilly Centre for Clinical Pharmacology. Purposes of the role include:\n• Develops or assists in the development of DHT trial protocol designs, clinical plans, and data analysis plans in collaboration with physicians, and/or medical colleagues.\n• Responsible for working with DHR&D broader team to analyze, report and readout data for DHT studies and DHT impacts in LY trials.\n• Influence team members regarding appropriate research methods\n\nPrimary Responsibilities:\n\nThe job tasks listed below outline the scope of the position. The application of these tasks may vary, based upon current business needs.\n\nDHT Trial Design and Analysis\n• Operate in collaboration with study personnel to provide input on study protocol, design studies and write protocols for the conduct of each study, from statistical analyst point of view.\n• Assist in or be accountable for selecting statistical methods for data analysis, authoring the corresponding sections of the protocol, and conducting the actual analysis.\n• Collaborate with data management in the planning and implementation of data quality assurance plans.\n• Maintain currency with respect to statistical methodology, to maintain proficiency in applying new and varied methods, and to be competent in justifying methods selected.\n• Participate in peer-review work products from other statistical colleagues (AADS, GSS, and LY trial project stats team).\n\nCommunication of Results and Inferences\n• As a Data Scientist, manage study analytics planning, tracking, and facilitation. Assist the development of DHT trial protocol designs, drive the data analysis plans, coordinate with cross-functional teams to define scope, timelines, and deliverables, while ensuring high quality data analytics for DHT study portfolio.\n• Provide strong leadership in the process of DHT development, by preparing databases, statistical summary table/figures in accordance with a schedule.\n• Collaborate with DHR&D team members to write reports and communicate results.\n• Assist with, or be responsible for, communicating study results via reports, manuscripts, or oral presentations in group settings, as well as for communicating one-on-one with key customers and presenting at scientific meetings.\n• Assist in response to regulatory queries and/or to interact with regulators from statistical analyst point of view.\n\nCollaboration and Continuous Improvement\n• Collaboration and Insight Development: Partner with internal and external SMEs to troubleshoot issues and work with data engineers to effectively leverage curated data, translating complex datasets into actionable insights.\n• Continuous Improvement: Proactively identify and implement enhancements in data processing efficiency, integrity, and quality with a sharp eye towards elevating the standards of our data handling practices in DHT trials\n\nAlgorithm Development and Testing\n• Rigorously test and validate the performance of developed algorithms across various datasets, ensuring their accuracy and reliability in real-world applications. This involves fine-tuning models for specific use cases, such as daily activity recognition and sleep detection, to enhance the overall effectiveness of sensor-based digital health technologies.\n\nWhat You Should Bring\n• Understand disease states in order to enhance the level of customer focus and collaboration and be seen as a strong scientific contributor.\n• Demonstrated communication, leadership, teamwork, project delivery, and problem solving skills.\n• Demonstrated ability to influence IT and business strategies to drive large-scale outcomes.\n• Validated skills of strong learning agility and relationship building to influence change using knowledge and relationships.\n• Successful record of high quality, user focused, on-time service and project delivery.\n• Excellent analytical, problem solving and communication skills, working across agile and diverse teams.\n• A high level of intellectual curiosity, external perspective, and innovation interest.\n• Demonstrated ability to communicate with a geographically dispersed group of business and technical colleagues.\n\nMinimum Qualification Requirements:\n• M.S. or Ph.D. in Statistics or Biostatistics or equivalent (Analytics, Informatics, Computer Science) with more than 5 Years of relevant experience\n• Strong programming skills, and knowledge of data structures and algorithms – Python/R, SQL.\n• Technical growth and application with working knowledge of experimental design and statistics.\n• Excellent software development experience and problem solving skillsets\n• Self-management skills with a focus on results for timely and accurate completion of competing deliverables\n• Teamwork and leadership skills\n\nOther Information/Additional Preferences:\n• Demonstrated ability to effectively partner/influence a team and drive a technical project to deliver results\n• Experience with application of data skills such as data flow, data quality & integrity, data interchange, data mining, and data representation principles\n• Understanding and experience in Time Series Analysis, Generative AI, prompt engineering, and Large Language Model (LLM).\n• A growth mindset and willingness to pick up new programming languages, technologies, and domain knowledge to be productive in role\n\nLocation: Singapore\n\nTime Type: Full time\n\nJob Type: Regular\n\nTravel: 0-10% travel required\n\nLilly is dedicated to helping individuals with disabilities to actively engage in the workforce, ensuring equal opportunities when vying for positions. If you require accommodation to submit a resume for a position at Lilly, please complete the accommodation request form (https://careers.lilly.com/us/en/workplace-accommodation) for further assistance. Please note this is for individuals to request an accommodation as part of the application process and any other correspondence will not receive a response.\n\nLilly does not discriminate on the basis of age, race, color, religion, gender, sexual orientation, gender identity, gender expression, national origin, protected veteran status, disability or any other legally protected status.\n\n#WeAreLilly',
  'apply_options': [{'title': 'Lilly Careers - Eli Lilly',
    'link': 'https://careers.lilly.com/us/en/job/R-98740/Digital-Health-R-D-Data-Scientist-Data-Analytics-and-Statistics?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Indeed',
    'link': 'https://sg.indeed.com/viewjob?jk=54b941fe81221df4&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'LinkedIn Singapore',
    'link': 'https://sg.linkedin.com/jobs/view/digital-health-r-d-%E2%80%93-data-scientist-%E2%80%93-data-analytics-and-statistics-at-eli-lilly-and-company-4346009994?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Glassdoor',
    'link': 'https://www.glassdoor.sg/job-listing/digital-health-r-and-d-%E2%80%93-data-scientist-%E2%80%93-data-analytics-and-statistics-eli-lilly-and-company-JV_IC3235921_KO0,71_KE72,93.htm?jl=1009978870088&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Jobs',
    'link': 'https://www.adzuna.sg/details/5557792636?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'NodeFlair',
    'link': 'https://nodeflair.com/jobs/eli-lilly-and-company-digital-health-r-d-data-scientist-data-analytics-and-statistics-410103?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'JobLeads',
    'link': 'https://www.jobleads.com/sg/job/digital-health-r-d-data-scientist-data-analytics-and-statistics--singapore--e89432dbbf0bbe79a26f04a343f1953a0?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'GrabJobs',
    'link': 'https://grabjobs.co/singapore/job/full-time/others/digital-health-randd-data-scientist-data-analytics-and-statistics-151786338?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}],
  'job_id': 'eyJqb2JfdGl0bGUiOiJEaWdpdGFsIEhlYWx0aCBSXHUwMDI2RCDigJMgRGF0YSBTY2llbnRpc3Qg4oCTIERhdGEgQW5hbHl0aWNzIGFuZCBTdGF0aXN0aWNzIiwiY29tcGFueV9uYW1lIjoiTGlsbHkiLCJhZGRyZXNzX2NpdHkiOiJTaW5nYXBvcmUiLCJodGlkb2NpZCI6IlhuWG9aOXpmUHFkdnNzcnJBQUFBQUE9PSIsInV1bGUiOiJ3K0NBSVFJQ0lKVTJsdVoyRndiM0psIiwiaGwiOiJlbiJ9'},
 {'title': 'Data Scientist',
  'company_name': 'changiairport',
  'location': 'Singapore',
  'via': 'Changiairport Jobs',
  'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Data+Scientist&htidocid=dxitauzZWedqfV4iAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXHsQoCMQwAUFzvE27K4iLYiuCiqyC43gccaQltpCalyXCjn64uD9702U37OzrCkpnE2RyO8NQERjhyBRV4qJZG8626d7vGaNZCMUfnHLK-owol3eJLk_1ZreKg3tBpPV9OW-hSDnOuKIWRR9fhwAILS8Ff6AuVGuCGgwAAAA&shmds=v1_AdeF8KjvoWIlCtlZtjE4DMc3aHHmcMNfjKOz4y5R44xh3JuTiw&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Data+Scientist&htidocid=dxitauzZWedqfV4iAAAAAA%3D%3D',
  'extensions': ['5 days ago', 'Full-time'],
  'detected_extensions': {'posted_at': '5 days ago',
   'schedule_type': 'Full-time'},

Check results in dataframe format.

In [4]:
import pandas as pd
import serpapi
from dotenv import load_dotenv
import os
from openai import OpenAI

load_dotenv()
SERPAPI_API_KEY = os.getenv('SERPAPI_API_KEY') 

client = OpenAI()

def get_refined_search_query(user_query: str):
    system_prompt = """
    You are an expert in extracting interpreting the preferred job position/role based on user input.
    Only output a clear job position to be used for Google search.
    """

    response = client.responses.create(
        model='gpt-5-nano',
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_query}
        ]
    )

    search_query = response.output_text
    return search_query

def scrape_google_jobs(query: str):
    refined_query = get_refined_search_query(query)
    print(f'Searching for: {refined_query}')
    search_params = {
        "engine": "google_jobs",
        "q": refined_query,
        "hl": "en",
        "location": "Singapore",
        "api_key": SERPAPI_API_KEY
    }

    results = serpapi.search(**search_params)
    jobs_results = results["jobs_results"]
    jobs_results_df = pd.DataFrame(jobs_results)
    return jobs_results_df

In [ ]:
query = 'find me ai engineer jobs in singapore'
jobs_results_df = scrape_google_jobs(query)
jobs_results_df

Searching for: AI Engineer Singapore

,title,company_name,location,via,share_link,extensions,detected_extensions,description,apply_options,job_id,thumbnail
0,"Associate, AI Engineer (Singapore)","Nomura Holdings, inc.",Singapore,Careers I NOMURA,https://www.google.com/search?ibp=htl;jobs&q=A...,"[10 days ago, Full-time]","{'posted_at': '10 days ago', 'schedule_type': ...",Job Title: AI Engineer\n\nCorporate Title: Ass...,"[{'title': 'Careers I NOMURA', 'link': 'https:...",eyJqb2JfdGl0bGUiOiJBc3NvY2lhdGUsIEFJIEVuZ2luZW...,NaN
1,"Senior/Lead AI Engineer, BCG X Singapore",Boston Consulting Group,Singapore,Boston Consulting Group,https://www.google.com/search?ibp=htl;jobs&q=A...,[Full-time],{'schedule_type': 'Full-time'},Who We Are\n\nBoston Consulting Group partners...,"[{'title': 'Boston Consulting Group', 'link': ...",eyJqb2JfdGl0bGUiOiJTZW5pb3IvTGVhZCBBSSBFbmdpbm...,https://serpapi.com/searches/695a3ee280f30ef50...
2,AI Engineer,Zoom,Singapore,Zoom Careers,https://www.google.com/search?ibp=htl;jobs&q=A...,"[23 days ago, Full-time]","{'posted_at': '23 days ago', 'schedule_type': ...","What you can expect\n\nAs an AI Engineer, you ...","[{'title': 'Zoom Careers', 'link': 'https://ca...",eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlciIsImNvbXBhbn...,NaN
3,"Engineer / Lead Engineer, Applied Vision AI R&...",Home Team Science and Technology Agency (HTX),Singapore,Careers@Gov,https://www.google.com/search?ibp=htl;jobs&q=A...,"[2 days ago, Full-time and Contractor]","{'posted_at': '2 days ago', 'schedule_type': '...",What the role is:\nHTX is the world’s first Sc...,"[{'title': 'Careers@Gov', 'link': 'https://job...",eyJqb2JfdGl0bGUiOiJFbmdpbmVlciAvIExlYWQgRW5naW...,https://serpapi.com/searches/695a3ee280f30ef50...
4,Senior Machine Learning/AI Engineer,Crédit Agricole CIB,Singapore,LinkedIn Singapore,https://www.google.com/search?ibp=htl;jobs&q=A...,"[5 days ago, Full-time]","{'posted_at': '5 days ago', 'schedule_type': '...",Who we are\n\nCrédit Agricole Corporate and In...,"[{'title': 'LinkedIn Singapore', 'link': 'http...",eyJqb2JfdGl0bGUiOiJTZW5pb3IgTWFjaGluZSBMZWFybm...,https://serpapi.com/searches/695a3ee280f30ef50...
5,"AI Engineer, Digital Energy",Schneider Electric,Singapore,Schneider Electric,https://www.google.com/search?ibp=htl;jobs&q=A...,"[26 days ago, Full-time]","{'posted_at': '26 days ago', 'schedule_type': ...",In Schneider Electric everything we do promote...,"[{'title': 'Schneider Electric', 'link': 'http...",eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlciwgRGlnaXRhbC...,NaN
6,AI Platform Engineer - ML Ops,Toku Pte Ltd,Anywhere,Indeed,https://www.google.com/search?ibp=htl;jobs&q=A...,"[2 days ago, Work from home, Full-time]","{'posted_at': '2 days ago', 'work_from_home': ...","At Toku, we create bespoke cloud communication...","[{'title': 'Indeed', 'link': 'https://sg.indee...",eyJqb2JfdGl0bGUiOiJBSSBQbGF0Zm9ybSBFbmdpbmVlci...,https://serpapi.com/searches/695a3ee280f30ef50...
7,(Senior) AI Engineer - BCG X Singapore,Boston Consulting Group,Singapore,Boston Consulting Group,https://www.google.com/search?ibp=htl;jobs&q=A...,[Full-time],{'schedule_type': 'Full-time'},Who We Are\n\nBoston Consulting Group partners...,"[{'title': 'Boston Consulting Group', 'link': ...",eyJqb2JfdGl0bGUiOiIoU2VuaW9yKSBBSSBFbmdpbmVlci...,https://serpapi.com/searches/695a3ee280f30ef50...
8,Solutions Engineer - Cloud & AI,Cisco,Singapore,Cisco Careers,https://www.google.com/search?ibp=htl;jobs&q=A...,"[17 days ago, Full-time, No degree mentioned]","{'posted_at': '17 days ago', 'schedule_type': ...","Your Impact\n\nAs a Solutions Engineer, you wi...","[{'title': 'Cisco Careers', 'link': 'https://c...",eyJqb2JfdGl0bGUiOiJTb2x1dGlvbnMgRW5naW5lZXIgLS...,https://serpapi.com/searches/695a3ee280f30ef50...
9,AI/ML Engineer-Contract,TANGSPAC CONSULTING PTE LTD,Singapore,MyCareersFuture,https://www.google.com/search?ibp=htl;jobs&q=A...,"[2 days ago, SGD 4.5K–SGD 6K a month, Contractor]","{'posted_at': '2 days ago', 'salary': 'SGD 4.5...",Responsibilities:\n• Manage and analyse busine...,"[{'title': 'MyCareersFuture', 'link': 'https:/...",eyJqb2JfdGl0bGUiOiJBSS9NTCBFbmdpbmVlci1Db250cm...,https://serpapi.com/searches/695a3ee280f30ef50...

In [7]:
query = 'find me ai engineer internships in singapore'
jobs_results_df = scrape_google_jobs(query)
jobs_results_df

Searching for: AI Engineer Internship Singapore

,title,company_name,location,via,share_link,extensions,detected_extensions,description,apply_options,job_id,thumbnail
0,Building AI Engineer Intern,Schneider Electric,Singapore,Schneider Electric,https://www.google.com/search?ibp=htl;jobs&q=A...,[Full-time and Internship],{'schedule_type': 'Full-time and Internship'},"In Schneider Electric, everything we do is gea...","[{'title': 'Schneider Electric', 'link': 'http...",eyJqb2JfdGl0bGUiOiJCdWlsZGluZyBBSSBFbmdpbmVlci...,NaN
1,Machine Learning and Generative AI Intern,Seagate Technology,Singapore,Seagate Careers,https://www.google.com/search?ibp=htl;jobs&q=A...,"[15 days ago, Internship]","{'posted_at': '15 days ago', 'schedule_type': ...",About our group:\n\nWe are the Global Factory ...,"[{'title': 'Seagate Careers', 'link': 'https:/...",eyJqb2JfdGl0bGUiOiJNYWNoaW5lIExlYXJuaW5nIGFuZC...,NaN
2,AI Engineer Intern,Singtel Group,Singapore,Singtel Career,https://www.google.com/search?ibp=htl;jobs&q=A...,"[18 days ago, Internship]","{'posted_at': '18 days ago', 'schedule_type': ...",Powering the Future with AIDA\n\nTo lead the n...,"[{'title': 'Singtel Career', 'link': 'https://...",eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlciBJbnRlcm4iLC...,https://serpapi.com/searches/695a407fe64250c16...
3,Summer Internship 2026 - AI and Gen AI Specialist,Income Insurance Limited,Singapore,Indeed,https://www.google.com/search?ibp=htl;jobs&q=A...,"[4 days ago, Full-time]","{'posted_at': '4 days ago', 'schedule_type': '...",We're seeking a talented and enthusiastic AI a...,"[{'title': 'Indeed', 'link': 'https://sg.indee...",eyJqb2JfdGl0bGUiOiJTdW1tZXIgSW50ZXJuc2hpcCAyMD...,https://serpapi.com/searches/695a407fe64250c16...
4,AI Researcher Intern (Embodied Robotics),PENTAS VISION PTE. LTD.,Singapore,MyCareersFuture,https://www.google.com/search?ibp=htl;jobs&q=A...,"[5 days ago, SGD 1.2K–SGD 1.8K a month, Intern...","{'posted_at': '5 days ago', 'salary': 'SGD 1.2...",Leveraging Sony’s world-leading sensor technol...,"[{'title': 'MyCareersFuture', 'link': 'https:/...",eyJqb2JfdGl0bGUiOiJBSSBSZXNlYXJjaGVyIEludGVybi...,NaN
5,CPS SG AI Engineer Intern,The Coca-Cola Company,Singapore,Built In,https://www.google.com/search?ibp=htl;jobs&q=A...,"[23 days ago, Internship]","{'posted_at': '23 days ago', 'schedule_type': ...",Location(s):\nSingapore\n\nCity/Cities:\nSinga...,"[{'title': 'Built In', 'link': 'https://builti...",eyJqb2JfdGl0bGUiOiJDUFMgU0cgQUkgRW5naW5lZXIgSW...,NaN
6,AI Systems Engineer Intern,DECIATO PTE. LTD.,Singapore,Indeed,https://www.google.com/search?ibp=htl;jobs&q=A...,"[SGD 2K–SGD 2.5K a month, Internship]","{'salary': 'SGD 2K–SGD 2.5K a month', 'schedul...",The Role: Supporting the Cognitive Platform\n\...,"[{'title': 'Indeed', 'link': 'https://sg.indee...",eyJqb2JfdGl0bGUiOiJBSSBTeXN0ZW1zIEVuZ2luZWVyIE...,NaN
7,Internship: Data/AI Engineer (May - Aug 2024),IBM,Singapore,WIZBII Jobs,https://www.google.com/search?ibp=htl;jobs&q=A...,[Internship],{'schedule_type': 'Internship'},"Job description\n\nIntroduction\nAt IBM, work ...","[{'title': 'WIZBII Jobs', 'link': 'https://en....",eyJqb2JfdGl0bGUiOiJJbnRlcm5zaGlwOiBEYXRhL0FJIE...,https://serpapi.com/searches/695a407fe64250c16...
8,Computer Vision Model Engineer Intern (Jan/Feb...,cynapse.ai,Singapore,LinkedIn Singapore,https://www.google.com/search?ibp=htl;jobs&q=A...,"[11 days ago, Internship]","{'posted_at': '11 days ago', 'schedule_type': ...",About Cynapse\n\nCynapse is a leading AI softw...,"[{'title': 'LinkedIn Singapore', 'link': 'http...",eyJqb2JfdGl0bGUiOiJDb21wdXRlciBWaXNpb24gTW9kZW...,https://serpapi.com/searches/695a407fe64250c16...
9,AI Engineering Intern (Computer Vision & Deep ...,Cynapse,Singapore,Glassdoor,https://www.google.com/search?ibp=htl;jobs&q=A...,"[SGD 1.1K–SGD 1.5K a month, Internship]","{'salary': 'SGD 1.1K–SGD 1.5K a month', 'sched...",About Cynapse\n\nCynapse is a leading AI softw...,"[{'title': 'Glassdoor', 'link': 'https://www.g...",eyJqb2JfdGl0bGUiOiJBSSBFbmdpbmVlcmluZyBJbnRlcm...,https://serpapi.com/searches/695a407fe64250c16...

In [33]:
jobs_results_df['extensions']

0                           [Full-time and Internship]
1                            [15 days ago, Internship]
2                            [18 days ago, Internship]
3                              [4 days ago, Full-time]
4    [5 days ago, SGD 1.2K–SGD 1.8K a month, Intern...
5                            [23 days ago, Internship]
6                [SGD 2K–SGD 2.5K a month, Internship]
7                                         [Internship]
8                            [11 days ago, Internship]
9              [SGD 1.1K–SGD 1.5K a month, Internship]
Name: extensions, dtype: object

In [34]:
jobs_results_df['detected_extensions']

0        {'schedule_type': 'Full-time and Internship'}
1    {'posted_at': '15 days ago', 'schedule_type': ...
2    {'posted_at': '18 days ago', 'schedule_type': ...
3    {'posted_at': '4 days ago', 'schedule_type': '...
4    {'posted_at': '5 days ago', 'salary': 'SGD 1.2...
5    {'posted_at': '23 days ago', 'schedule_type': ...
6    {'salary': 'SGD 2K–SGD 2.5K a month', 'schedul...
7                      {'schedule_type': 'Internship'}
8    {'posted_at': '11 days ago', 'schedule_type': ...
9    {'salary': 'SGD 1.1K–SGD 1.5K a month', 'sched...
Name: detected_extensions, dtype: object

In [27]:
jobs_results_df['extensions'].iloc[4]

['5 days ago', 'SGD\xa01.2K–SGD\xa01.8K a month', 'Internship']

In [38]:
jobs_results_df['detected_extensions'].iloc[3]

{'posted_at': '4 days ago', 'schedule_type': 'Full-time'}

In [44]:
salary = jobs_results_df['detected_extensions'].iloc[4].get('salary')
posted_at = jobs_results_df['detected_extensions'].iloc[4].get('posted_at')

salary, posted_at

('SGD 1.2K–SGD 1.8K a month', '5 days ago')

# Pydantic

Pydantic is used for validation and quality control to ensure data consistency.

In [19]:
from pydantic import BaseModel
from typing import List, Optional

class JobResult(BaseModel):
    title: str
    company: str
    location: str
    link: str
    description: str
    salary: Optional[str] = None
    posted_at: Optional[str] = None

In [51]:
def scrape_google_jobs(query: str):
    refined_query = get_refined_search_query(query)
    print(f'Searching for: {refined_query}')
    search_params = {
        "engine": "google_jobs",
        "q": refined_query,
        "hl": "en",
        "location": "Singapore",
        "api_key": SERPAPI_API_KEY
    }

    results = serpapi.search(**search_params)
    jobs_results = results["jobs_results"]
    jobs_results_df = pd.DataFrame(jobs_results)

    clean_jobs = []
    for idx, row in jobs_results_df.iterrows():
        job = JobResult(
            title=row['title'],
            company=row['company_name'],
            location=row['location'],
            link=row['share_link'],
            description=row['description'],
            salary=row['detected_extensions'].get('salary'),
            posted_at=row['detected_extensions'].get('posted_at')
        )
        clean_jobs.append(job)

    return clean_jobs

In [52]:
query = 'find me ai engineer internships in singapore'
jobs = scrape_google_jobs(query)
jobs

Searching for: AI Engineer Internships Singapore

[JobResult(title='Building AI Engineer Intern', company='Schneider Electric', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internships+Singapore&htidocid=DadXvTo8Iylc87d0AAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXOsQrCMBCAYVz7CC7eLNhIwUUnhSJ17QOUND2Sk3gXcif0OXxidfnX728-m6a7vSkvxBGuA_QciRErDGxYGQ7wkBkUfQ0JhOEuEjNuL8ms6Nk51dxGNW8U2iAvJ4yzrO4ps_4zafIVS_aGU3c6rm3huN-NITHS8lP6jMEqBSCG8bfgi1T8AuL8N8-VAAAA&shmds=v1_AdeF8KhCca_MmrgCy7a9dEsnd5WbJcoCeI3CLWrZxct5m1jHjQ&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internships+Singapore&htidocid=DadXvTo8Iylc87d0AAAAAA%3D%3D', description="In Schneider Electric, everything we do is geared towards advancing progress and sustainability for all—our colleagues, customers, partners, and the communities and societies we serve.\n\nWhether it's through our products, software, and services that propel the digital transformation of energy management and automation, or through our corporate citizenship and volunteer activities, we make a meaningful impact by empowering people and organizations to become more resilient, electric, and digital.\n\nWhich is where you come in. Working at Schneider Electric means working toward a cleaner, better world. You are part of a global team built on inclusion, mastery, purpose, action, curiosity, and teamwork, turning sustainability ambitions into actions.\n\nWe are now hiring interns for our H1 2026 cohort! Internships will start in 2 batches: January 2026 or February 2026. Please indicate your exact availability in your application. Students who can commit full-time will be preferred.\n\nJoin us as an Building AI Engineer Intern to make an impact!\n\nLocation: Kallang\n\nThe Role:\n\nWhat will you do?\n• Design, develop, and deploy AI models for predictive maintenance, energy optimization, occupancy analytics, and fault detection in building systems\n• Work with BMS, EMS, IoT sensors, and other building data sources to collect, clean, and structure data for AI applications\n• Collaborate with software engineers and solution architects to integrate AI models into scalable platforms and edge devices\n• Stay ahead of industry trends and emerging technologies in AI, smart buildings, and energy management\n• Prototype new solutions and validate them through pilot projects\n• Work closely with internal teams, clients, and partners to understand requirements, present solutions, and ensure successful implementation\n• Ensure AI solutions comply with data privacy regulations, cybersecurity standards, and ethical AI practices\n\nWhat qualifications will make you successful?\n• Bachelor’s or Master’s degree in Computer Science, Electrical Engineering, Data Science, or related fields\n\nSkills/Systems knowledge:\n• 2 years of experience in AI/ML development, preferably in building automation, energy systems, or smart infrastructure\n• Proficiency in Python, TensorFlow/PyTorch, and data engineering tools\n• Familiarity with building systems (HVAC, lighting, access control), BMS/EMS platforms, and IoT protocols\n• Experience with cloud platforms (Azure, AWS, GCP) and edge computing\n• Strong analytical, problem-solving, and communication skills\n\nWhat’s in it for me?\n• Global Family Leave\n• Comprehensive medical coverage for employee and dependents\n• Worldwide Employee Stock Ownership\n• Hybrid work arrangement (New Ways of Working)\n• …and more!\n\nLooking to make an IMPACT with your career?\n\nWhen you are thinking about joining a new team, culture matters. At Schneider Electric, our values and behaviors are the foundation for creating a great culture to support business success. We believe that our IMPACT values – Inclusion, Mastery, Purpose, Action, Curiosity, Teamwork – starts with us.\n\nIMPACT is also your invitation to join Schneider Electric where you can contribute to turning sustainability ambition into actions, no matter what role you play. It is a call to connect your career with the ambition of achieving a more resilient, efficient, and sustainable world.\n\nWe are looking for IMPACT Makers; exceptional people who turn sustainability ambitions into actions at the intersection of automation, electrification, and digitization. We celebrate IMPACT Makers and believe everyone has the potential to be one.\n\nBecome an IMPACT Maker with Schneider Electric – apply today!\n\n€36 billion global revenue\n+13% organic growth\n150 000+ employees in 100+ countries\n#1 on the Global 100 World’s most sustainable corporations\n\nYou must submit an online application to be considered for any position with us. This position will be posted until filled.\n\nSchneider Electric aspires to be the most inclusive and caring company in the world, by providing equitable opportunities to everyone, everywhere, and ensuring all employees feel uniquely valued and safe to contribute their best. We mirror the diversity of the communities in which we operate, and ‘inclusion’ is one of our core values. We believe our differences make us stronger as a company and as individuals and we are committed to championing inclusivity in everything we do.\n\nAt Schneider Electric, we uphold the highest standards of ethics and compliance, and we believe that trust is a foundational value. Our Trust Charter is our Code of Conduct and demonstrates our commitment to ethics, safety, sustainability, quality and cybersecurity, underpinning every aspect of our business and our willingness to behave and respond respectfully and in good faith to all our stakeholders. You can find out more about our Trust Charter here\n\nSchneider Electric is an Equal Opportunity Employer. It is our policy to provide equal employment and advancement opportunities in the areas of recruiting, hiring, training, transferring, and promoting all qualified individuals regardless of race, religion, color, gender, disability, national origin, ancestry, age, military status, sexual orientation, marital status, or any other legally protected characteristic or conduct.", salary=None, posted_at=None),
 JobResult(title='AI Engineer Intern', company='Singtel Group', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internships+Singapore&htidocid=GIPB2X16kK4je5IQAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXIsQrCMBAAUFz7CZ1uVTARwUUnByl19QNKEo4kEu_C3Qn9AD9curzhDb_dsL_P8KBcCVFgJkMhOMKTIygGSQWYYGLODcdbMet69V61uawWrCaX-OOZMPLq3xx1Y9ESBHsLhsv5clpdp3wYX5WyYYNJ-NuhEmwROgv-AU_HkPaHAAAA&shmds=v1_AdeF8KjpNb5QExqzwG3F2iFvVKsUP1wr9q_Ql03TqFxdmQCFJA&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internships+Singapore&htidocid=GIPB2X16kK4je5IQAAAAAA%3D%3D', description='Powering the Future with AIDA\n\nTo lead the next phase of our AI evolution, we’ve launched a new business unit AIDA – Artificial Intelligence & Data Analytics – a strategic engine driving our transformation designed to scale our AI ambitions with precision and purpose. This marks a pivotal shift in how we operate, innovate, and serve to embed intelligence into every layer of our business.\n\nAt Singtel, this is more than a technology upgrade. It’s a strategic transformation that redefines how value is created across the enterprise core— augmenting human capabilities and unlocking entirely new potential. It is a transformation journey by aligning people, platforms, and processes under one cohesive strategy. Our mission is to build AI literacy, and foster a culture where intelligence empowers people.\n\nWe welcome you to join us on a transformational journey that’s reshaping the telecommunications industry — and redefining what’s possible with AI at its core. Grow with us in a workplace that champions innovation, embraces agility, and puts human potential at the heart of everything we do.\n\nBe a Part of Something BIG!\n\nThe AI Engineer Intern will support the development, testing, and experimentation of next-generation AI solutions within AIDA, including Singtel’s pioneering AI innovations. The intern will engage in hands-on prototyping (“vibe coding”), explore new AI/GenAI tools, and assist engineers in building lightweight workflows, models, and applications.\n\nThis role offers a unique opportunity to gain practical exposure to AI engineering, rapid experimentation, and enterprise AI product development while contributing to real initiatives that shape how employees interact with AI across Singtel.\n\nMake an Impact by:\n• Support the development and prototyping of new AI and GenAI concepts, including early versions of the AI Avatar and related features.\n• Explore, evaluate, and experiment with AI tools, libraries, frameworks, and agentic AI capabilities to test feasibility and potential value.\n• Assist AI engineers with data preparation, prompt experimentation, model testing, and integration validation.\n• Act as an early-stage tester for new AI solutions to identify bugs, usability issues, and improvement opportunities.\n• Contribute to building lightweight scripts, workflows, or applications to demonstrate concepts and accelerate iteration.\n• Document findings, experiment results, and technical learnings to support engineering refinement and decision-making.\n• Collaborate with solution architects and AI engineers to understand requirements and contribute to iterative development.\n\nSkills for Success:\n• Bachelor’s or Master’s degree in Computer Science, Engineering, Data, AI/ML or related field.Master’s degree in AI, Tech Management, or Business Analytics.\n• Undergraduate degree in progress (Computer Science, Engineering, AI/ML, Data Science, or related fields). Prior internship or project experience in AI, GenAI, or software development.\n• Basic Python programming skills.\n• Familiarity with notebooks, APIs, or ML libraries.\n• Understanding of prompt engineering basics.\n• Ability to explore and test AI tools and frameworks. Exposure to LangChain/LangGraph or agentic AI tools.\n• Experience building lightweight apps or scripts.\n• Knowledge of cloud or container tools.\n• Curious, proactive learner with strong analytical thinking.\n• Comfortable with hands-on experimentation and rapid iteration.\n• Good communication and documentation habits.\n• Collaborative mindset when working with engineers. Interest in user experience or product thinking.\n\nAre you ready to say hello to BIG Possibilities?\n\nTake the leap with Singtel to unlock new opportunities and accelerate your growth. Apply now and start your empowering career!', salary=None, posted_at='18 days ago'),
 JobResult(title='Machine Learning and Generative AI Intern', company='Seagate Technology', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internships+Singapore&htidocid=eyVOYFyVHmLSEHIRAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xWOMQoCMRBFsd0j2Di14EYEG220Wla0WvtlNg5JJM6ETJD1Nh7V2Pzi8R785rtoTje0PjDBlTBzYAfID-iIKWMJb4JzDz0XygwbuMgEWj3rQRg6ERdpefSlJD0Yoxpbp6VmtrXyMsI0yWyeMul_RvWYKUUsNO7227lN7NargdBVAneyniWK-0BgGOoRTJLpBxh5skqjAAAA&shmds=v1_AdeF8KjjY8jW8Y8i_E65jsxGbepcqGhTz2KiFfpZfS2t-JMOMQ&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internships+Singapore&htidocid=eyVOYFyVHmLSEHIRAAAAAA%3D%3D', description="About our group:\n\nWe are the Global Factory Information Technologies (GFIT) team at Seagate. Our mission is to drive digital transformation across Seagate’s global manufacturing operations. We develop and implement data-driven solutions that enable real-time decision-making, predictive analytics, and intelligent automation.\n\nIn 2026, we are expanding our focus to include Generative AI (GenAI) as a core enabler of smart factory innovation. This includes using GenAI to enhance process optimization, automate knowledge generation, and create intelligent digital assistants that support factory operations.\n\nAbout the role - you will:\n\nAs an AI Intern specializing in Generative AI, you will collaborate with our Data Scientists and Engineers to explore and develop innovative GenAI applications for smart manufacturing. Your responsibilities may include:\n• Designing and prototyping GenAI models for factory use cases.\n• Developing AI-powered tools for automated report generation, anomaly explanation, and digital twin simulations.\n• Integrating GenAI solutions with factory control systems..\n\nThis is a high-impact role where your work will contribute to Seagate’s next-generation smart factory capabilities.\n\nAbout you:\n\nWe are looking for candidates who are passionate about AI and excited to explore the frontiers of Generative AI in real-world industrial settings. You should be:\n• Curious, inventive, and eager to learn.\n• Comfortable working independently and collaboratively in a fast-paced environment.\n• Good at Python programming and familiar with GenAI frameworks\n• Knowledgeable in machine learning, deep learning, and natural language processing.\n• Bachelor or master's students in Computer science, computer engineering\n\nYour experience includes:\n\nLocation:\n\nLocation: Woodlands, Singapore, W3\n\nTravel: None", salary=None, posted_at='15 days ago'),
 JobResult(title='AI Engineering Intern', company='Urban Redevelopment Authority', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internships+Singapore&htidocid=EmeBOT7JCamuGYIQAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXOsQrCMBAAUFz7CU43F01EcNGpg0gdFeeS1COJpHfhckr9En9XXd78ms-iWXU9HCkkQpREAXpSFII1nNlDRSdjBCY4MYeMy0NULXVvba3ZhKpO02hGniwTep7tg339M9ToBEt2isN2t5lNodC2N_GO4IJ3fGHmMiEpdE-NLEnfkAiuv4ErLPgFM7qJMpoAAAA&shmds=v1_AdeF8KhC2vpKsJVvOPDJ29xKcK3pIMNa3b8se-EJ4TUo6nh45A&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internships+Singapore&htidocid=EmeBOT7JCamuGYIQAAAAAA%3D%3D', description="What the role is:\nURA has undergone a digitalisation journey to harness urban science, geospatial and data analytics, modelling and simulation, and AI technologies in urban planning and design. Our teams, with capabilities in data policy, governance, strategy, and engineering, product strategy, business analysis, software engineering, cloud engineering, urban design technologies, data science, AI/ML, and modelling and simulation, collaborate with planners, architects, and policymakers to create insights and digital solutions for Singapore’s urban planning challenges. You will be joining the PLAN AI Team, building Artificial Intelligence (AI)-enabled planning system & processes. This is part of the National AI Strategy and the MND Science & Technology Plan, focusing on strengthening central support for AI, building WOG AI Capabilities, and establishing a Public Sector AI Governance Framework.\n\nWhat you will be working on:\nThe fast-paced developments in the space of AI presents exciting opportunities to harness this technology to enhance the way URA officers work. Intern(s) will undertake some of or a mix of the following tasks:\n\n• support development and production of AI/ML tools to enhance urban planning & design work (e.g. LLM-enabled assistants, AI image generator [model training + explore latest diffusion models] etc)\n• exploration of new AI/ML techniques such as Text2SQL, RAG2SQL, multi-agent AI systems (or others) etc.\n\nLearning Outcomes:\n• Gain practical experience in developing and implementing AI/ML/LLM-enabled prototypes and solutions within Gov/URA's context.\n• Cultivate problem-solving and innovative thinking skills, particularly in proposing solutions to address users' needs.\n• Collaborate with cross-functional teams to design and implement solutions that meet business requirements\n\nWhat we are looking for:\n• Internship Period: May - Aug 2026. Full-time internship preferred.\n• Students pursuing Computer Science/ Information Technology with interest in AI/ML & GenAI, Smart Cities, Design & Artificial Intelligence\n• Familiarity with RAG techniques. Experience with UX/UI design and design tools like Canva will be a bonus\n\nNote: To facilitate the hiring process, please state your availability, including specific start and end date in your resume or application form.\n\nWe regret to inform that only shortlisted candidates will be notified.\n\nKindly note the selection process for this role will commence in Jan 2026.\n\nAbout Urban Redevelopment Authority\nThe Urban Redevelopment Authority (URA) is Singapore's national land use planning authority. URA prepares long term strategic plans, as well as detailed local area plans, for physical development, and then co-ordinates and guides efforts to bring these plans to reality. Prudent land use planning has enabled Singapore to enjoy strong economic growth and social cohesion, and ensures that sufficient land is safeguarded to support continued economic progress and future development.", salary=None, posted_at=None),

In [58]:
import json

json.loads(jobs[0].model_dump_json())

{'title': 'Building AI Engineer Intern',
 'company': 'Schneider Electric',
 'location': 'Singapore',
 'link': 'https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internships+Singapore&htidocid=DadXvTo8Iylc87d0AAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXOsQrCMBCAYVz7CC7eLNhIwUUnhSJ17QOUND2Sk3gXcif0OXxidfnX728-m6a7vSkvxBGuA_QciRErDGxYGQ7wkBkUfQ0JhOEuEjNuL8ms6Nk51dxGNW8U2iAvJ4yzrO4ps_4zafIVS_aGU3c6rm3huN-NITHS8lP6jMEqBSCG8bfgi1T8AuL8N8-VAAAA&shmds=v1_AdeF8KhCca_MmrgCy7a9dEsnd5WbJcoCeI3CLWrZxct5m1jHjQ&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internships+Singapore&htidocid=DadXvTo8Iylc87d0AAAAAA%3D%3D',
 'description': "In Schneider Electric, everything we do is geared towards advancing progress and sustainability for all—our colleagues, customers, partners, and the communities and societies we serve.\n\nWhether it's through our products, software, and services that propel the digital transformation of energy management and automation, or through our corporate citizenship and volunteer activities, we make a meaningful impact by empowering people and organizations to become more resilient, electric, and digital.\n\nWhich is where you come in. Working at Schneider Electric means working toward a cleaner, better world. You are part of a global team built on inclusion, mastery, purpose, action, curiosity, and teamwork, turning sustainability ambitions into actions.\n\nWe are now hiring interns for our H1 2026 cohort! Internships will start in 2 batches: January 2026 or February 2026. Please indicate your exact availability in your application. Students who can commit full-time will be preferred.\n\nJoin us as an Building AI Engineer Intern to make an impact!\n\nLocation: Kallang\n\nThe Role:\n\nWhat will you do?\n• Design, develop, and deploy AI models for predictive maintenance, energy optimization, occupancy analytics, and fault detection in building systems\n• Work with BMS, EMS, IoT sensors, and other building data sources to collect, clean, and structure data for AI applications\n• Collaborate with software engineers and solution architects to integrate AI models into scalable platforms and edge devices\n• Stay ahead of industry trends and emerging technologies in AI, smart buildings, and energy management\n• Prototype new solutions and validate them through pilot projects\n• Work closely with internal teams, clients, and partners to understand requirements, present solutions, and ensure successful implementation\n• Ensure AI solutions comply with data privacy regulations, cybersecurity standards, and ethical AI practices\n\nWhat qualifications will make you successful?\n• Bachelor’s or Master’s degree in Computer Science, Electrical Engineering, Data Science, or related fields\n\nSkills/Systems knowledge:\n• 2 years of experience in AI/ML development, preferably in building automation, energy systems, or smart infrastructure\n• Proficiency in Python, TensorFlow/PyTorch, and data engineering tools\n• Familiarity with building systems (HVAC, lighting, access control), BMS/EMS platforms, and IoT protocols\n• Experience with cloud platforms (Azure, AWS, GCP) and edge computing\n• Strong analytical, problem-solving, and communication skills\n\nWhat’s in it for me?\n• Global Family Leave\n• Comprehensive medical coverage for employee and dependents\n• Worldwide Employee Stock Ownership\n• Hybrid work arrangement (New Ways of Working)\n• …and more!\n\nLooking to make an IMPACT with your career?\n\nWhen you are thinking about joining a new team, culture matters. At Schneider Electric, our values and behaviors are the foundation for creating a great culture to support business success. We believe that our IMPACT values – Inclusion, Mastery, Purpose, Action, Curiosity, Teamwork – starts with us.\n\nIMPACT is also your invitation to join Schneider Electric where you can contribute to turning sustainability ambition into actions, no matter what role you play. It is a call to connect your career with the ambition of achieving a more resilient, efficient, and sustainable world.\n\nWe are looking for IMPACT Makers; exceptional people who turn sustainability ambitions into actions at the intersection of automation, electrification, and digitization. We celebrate IMPACT Makers and believe everyone has the potential to be one.\n\nBecome an IMPACT Maker with Schneider Electric – apply today!\n\n€36 billion global revenue\n+13% organic growth\n150 000+ employees in 100+ countries\n#1 on the Global 100 World’s most sustainable corporations\n\nYou must submit an online application to be considered for any position with us. This position will be posted until filled.\n\nSchneider Electric aspires to be the most inclusive and caring company in the world, by providing equitable opportunities to everyone, everywhere, and ensuring all employees feel uniquely valued and safe to contribute their best. We mirror the diversity of the communities in which we operate, and ‘inclusion’ is one of our core values. We believe our differences make us stronger as a company and as individuals and we are committed to championing inclusivity in everything we do.\n\nAt Schneider Electric, we uphold the highest standards of ethics and compliance, and we believe that trust is a foundational value. Our Trust Charter is our Code of Conduct and demonstrates our commitment to ethics, safety, sustainability, quality and cybersecurity, underpinning every aspect of our business and our willingness to behave and respond respectfully and in good faith to all our stakeholders. You can find out more about our Trust Charter here\n\nSchneider Electric is an Equal Opportunity Employer. It is our policy to provide equal employment and advancement opportunities in the areas of recruiting, hiring, training, transferring, and promoting all qualified individuals regardless of race, religion, color, gender, disability, national origin, ancestry, age, military status, sexual orientation, marital status, or any other legally protected characteristic or conduct.",
 'salary': None,
 'posted_at': None}

Convert raw JSON consisting of jobs (extracted from SerpAPI) into Pydantic objects.

In [9]:
search_params = {
    "engine": "google_jobs",
    "q": 'Machine Learning Engineer',
    "hl": "en",
    "location": "Singapore",
    "api_key": SERPAPI_API_KEY
}

results = serpapi.search(**search_params)
jobs_results = results.get('jobs_results')
jobs_results

[{'title': 'Principal Machine Learning System Engineer',
  'company_name': 'Atlassian',
  'location': 'Singapore',
  'via': 'Join Our Talent Community | Atlassian Careers Apply - Atlassian',
  'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Machine+Learning+Engineer&htidocid=hmrzybxb-pIZD7iaAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xWNMQrCQBAAsc0DLKy2FsyJYKNViiCIgpAHhM2x3K1cdo_bK-JPfK6xmWKmmOa7abpXYfGcMcETfWQheBAWYQkwfKzSDL2EVVOBA9x1Aluzj6ACN9WQaHeNtWa7OGeW2mAVK_vW6-xUaNLFvXWyP0aLWCgnrDSezselzRL2264mNGMUYIFh3WLWQj8wJe5lmwAAAA&shmds=v1_AdeF8KgrPu3QG_JOgGfeSmSElJhhiLI16JeRz-fSgfPRagzIvw&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Machine+Learning+Engineer&htidocid=hmrzybxb-pIZD7iaAAAAAA%3D%3D',
  'extensions': ['Full-time'],
  'detected_extensions': {'schedule_type': 'Full-time'},
  'description': 'Overview\n\nWorking at Atlassian\n\nAtlassians can choose where they work – whether in an office, from home, or a combination of the two. That way, Atlassians have more control over supporting their family, personal goals, and other priorities. We can hire people in any country where we have a legal entity. Interviews and onboarding are conducted virtually, a part of being a distributed-first company.\n\nResponsibilities\n\nAbout Atlassian\n\nAtlassian\'s mission, "to unleash the potential of every team," serves as the foundation of everything we do. We have developed well-known collaborative products, such as Jira, Confluence, and Bitbucket, that fit into the fabric of teamwork across different types of teams and the processes to help every team succeed.\n\nAtlassian helps teams everywhere change the world. Our products power revolutions across many industries, enabling teams to collaborate effectively and achieve their highest potential. Take, for example, NASA launching the Rover on Mars or Cochlear gifting those born deaf with the ability to hear. Your work directly impacts the products they use to promote humanity.\nAbout Central AI Org\n\nOur organization is dedicated to driving AI innovation across all Atlassian products and platforms. We aim to deliver seamless AI experiences while establishing a robust Atlassian AI infrastructure for the future. Our purpose is to:\n• Develop horizontal AI capabilities and infrastructure that can be leveraged across all products.\n• Establish a centralized Search, Q&A, and Conversational AI system that integrates seamlessly with all Atlassian products.\n• Explore the integration of Atlassian products with AI solutions beyond the Atlassian ecosystem.\n\nAbout AI & ML Platform Team\n\nOur team’s goal is to build the foundations to democratize AI and Machine Learning for Atlassian’s teams, customers, and ecosystem. We aim to build productive and reliable tools that empower Atlassian teams to harness the power of AI. These tools will facilitate the development, deployment, measurement, and operation of AI & ML experiences.\n\nOur tools are designed to integrate seamlessly with other Atlassian platforms, including the Atlassian Data Platform. This integration enables teams to efficiently and swiftly incorporate AI and ML capabilities into their workflows while strictly adhering to all security and data usage policies. Our primary goal is to deliver a smooth and hassle-free experience for Atlassian users, empowering them to harness the potential of AI and ML without any complications.\nAbout This Role\n\nAs a Principal Machine Learning System Engineer on the AI & ML Platform team, you will play a pivotal role in developing and refining the core infrastructure that empowers all Atlassian software engineers, ML engineers, and data scientists to create, train, evaluate, deploy, and manage Machine Learning models and pipelines.\n\nYou will collaborate closely with product teams, such as Jira and Confluence, to solve their specific challenges in building ML solutions. This may involve curating high-quality ML datasets, fine-tuning open-sourced Large Language Models (LLMs), or accessing proprietary LLMs. Your expertise in both ML and software development expertise will be instrumental in overcoming challenging problems and navigating complex infrastructure and architectural issues.\n\nThis position offers you the chance to lead projects from the technical design phase all the way to launch. You will partner with various teams and internal stakeholders to achieve impactful results.\n\nIn this role, you\'ll get the chance to:\n• Collaborate with your teammates to solve complex problems, from technical design to launch.\n• Deliver cutting-edge solutions that are used by other Atlassian teams and products to build AI features that reach millions of customers.\n• Deliver code reviews, documentation & bug fixes within a strong engineering culture\n• Partner across engineering teams to take on company-wide initiatives spanning multiple projects.\n• Mentor junior members of the team.\n\nOn your first day, we’ll expect you to have\n• Extensive experience in building Machine Learning and AI infra/platform/system (generally 5+ years)\n• Comprehensive ML lifecycle expertise: proven experience developing, deploying, and maintaining end-to-end ML systems, from data engineering to model serving and monitoring.\n• Large-scale system design: Extensive experience designing and building scalable, fault-tolerant, and high-performance distributed systems for machine learning.\n• Proficiency with frameworks and languages: Expert-level proficiency in Python and ML frameworks like PyTorch, TensorFlow, or JAX. Familiarity with other languages like Go, Java, or Scala is also beneficial.\n• MLOps and automation: Deep experience implementing MLOps, CI/CD pipelines, and automation for continuous training, deployment, and monitoring of ML models.\n\nIt would be great, but not required if you have\n• Cloud infrastructure: Hands-on expertise with major cloud platforms such as AWS, GCP, or Azure, including their specific AI/ML services and compute resources like GPUs.\n• Big data processing: Experience with distributed computing frameworks for large-scale data processing, such as Spark, Ray, or Dask.\n• Performance optimization: A demonstrated ability to diagnose and solve complex performance and optimization problems for ML models and infrastructure.\n• Generative AI systems: Experience with GenAI frameworks and tools, including developing and fine-tuning large language models (LLMs) and building retrieval-augmented generation (RAG) systems.\n\nQualifications\n\nBenefits & Perks\n\nAtlassian offers a wide range of perks and benefits designed to support you, your family and to help you engage with your local community. Our offerings include health and wellbeing resources, paid volunteer days, and so much more. To learn more, visit go.atlassian.com/perksandbenefits.\n\nAbout Atlassian\n\nAt Atlassian, we\'re motivated by a common goal: to unleash the potential of every team. Our software products help teams all over the planet and our solutions are designed for all types of work. Team collaboration through our tools makes what may be impossible alone, possible together.\n\nWe believe that the unique contributions of all Atlassians create our success. To ensure that our products and culture continue to incorporate everyone\'s perspectives and experience, we never discriminate based on race, religion, national origin, gender identity or expression, sexual orientation, age, or marital, veteran, or disability status. All your information will be kept confidential according to EEO guidelines.\n\nTo provide you the best experience, we can support with accommodations or adjustments at any stage of the recruitment process. Simply inform our Recruitment team during your conversation with them.\n\nTo learn more about our culture and hiring process, visit go.atlassian.com/crh.',
  'apply_options': [{'title': 'Join Our Talent Community | Atlassian Careers Apply - Atlassian',
    'link': 'https://join.atlassian.com/jobs/22598?lang=en-us&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Indeed',
    'link': 'https://sg.indeed.com/viewjob?jk=283c61f4ef488c39&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Glassdoor',
    'link': 'https://www.glassdoor.sg/job-listing/principal-machine-learning-system-engineer-atlassian-JV_IC3235921_KO0,42_KE43,52.htm?jl=1009893404749&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Built In',
    'link': 'https://builtin.com/job/principal-machine-learning-system-engineer/7284978?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Built In Singapore',
    'link': 'https://builtinsingapore.com/job/principal-machine-learning-system-engineer/7284978?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Bayt.com',
    'link': 'https://www.bayt.com/en/singapore/jobs/principal-machine-learning-system-engineer-73802853/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'Atlassian Jobs: View Listings For Open Positions - ICIMS',
    'link': 'https://globalcareers-atlassian.icims.com/jobs/22597/principal-machine-learning-system-engineer/job?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'BeBee SG',
    'link': 'https://sg.bebee.com/job/8957231a7508315a1e6a87d5a965aac2?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}],
  'job_id': 'eyJqb2JfdGl0bGUiOiJQcmluY2lwYWwgTWFjaGluZSBMZWFybmluZyBTeXN0ZW0gRW5naW5lZXIiLCJjb21wYW55X25hbWUiOiJBdGxhc3NpYW4iLCJhZGRyZXNzX2NpdHkiOiJTaW5nYXBvcmUiLCJodGlkb2NpZCI6Imhtcnp5YnhiLXBJWkQ3aWFBQUFBQUE9PSIsInV1bGUiOiJ3K0NBSVFJQ0lKVTJsdVoyRndiM0psIiwiaGwiOiJlbiJ9'},
 {'title': 'Senior Machine Learning/AI Engineer',
  'company_name': 'Crédit Agricole CIB',
  'location': 'Singapore',
  'via': 'LinkedIn Singapore',
  'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Machine+Learning+Engineer&htidocid=mMgF3XD292ItDP2NAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xWNsQ3CMBAARZsRqJ4WiRgh0YQKIoSCoMoAkWNetpH5t_5dZBgWYA4WIzRX3BVXvRdV0yNFFrhbFyIh3NAKRfLm2MGZ_KxQYANXHkHn5AIwwYXZJ1weQilZG2NUU-212BJd7fhlmHDkyTx51D8GDVYwJ1tw2O23U53Jr1etfD-PWODoJTpOCG13gkjQz3ebWfAHHWh14J8AAAA&shmds=v1_AdeF8KilK3BlsmwXKCpWq-Is-xY_-2cMmnuMDXYlg1iEbgfGRA&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Machine+Learning+Engineer&htidocid=mMgF3XD292ItDP2NAAAAAA%3D%3D',
  'thumbnail': 'https://serpapi.com/searches/695a63987d6e700c1afa5109/images/30df5819a7c8638190ee171e28217b897639f7c8f9f48f3fdbe08871a090518a.jpeg',
  'extensions': ['5 days ago', 'Full-time'],
  'detected_extensions': {'posted_at': '5 days ago',
   'schedule_type': 'Full-time'},
  'description': "Who we are\n\nCrédit Agricole Corporate and Investment Banking (Crédit Agricole CIB) is the corporate and investment banking arm of Crédit Agricole Group, world’s 10th largest bank by total assets.\n\nOur Singapore center is the 2nd largest IT setup (after Paris Head Office) for Crédit Agricole CIB's worldwide business. We work daily with international branches located in 30 markets by:\n• Envisioning and preparing the Bank’s futures information systems\n• Partnering and supporting core banking flagships and transverse areas in their large scale development projects\n• Providing premium In-house Banking applications\n\nThis unique positioning empowers us to bring our core banking business a sustainable competitive advantage on the market.\n\nWe seek innovative and agile people sharing our mindset to support ambitious and forthcoming technological challenges.\n\nPosition\n\nIn a challenging and multicultural environment, we are looking for a Senior Machine Learning/AI Engineer to join our Digital Excellence Centre (DEC) department of Crédit Agricole CIB. The department handles the development of transversal and international projects.\n\nWe are looking for a Builder-type AI Engineer with a strong background in Traditional ML and GenAI (LLM,Agentic), who can design, build, and deploy end-to-end machine learning solutions. This hybrid role requires a hands-on expert who can not only build models when needed but also engineer scalable, production-grade ML systems while adhering to the organization's AI governance and compliance standards.\n\nMain responsibilities\n• As a Senior AI Engineer, you’ll be part of growing engineering team and help to build the next generation AI Solutions.\n• Collaborate with business stakeholders to understand use cases and define AI solution; work on Proof of Concepts wherever needed\n• Engineer and deploy ML models into production using MLOps best practices (model versioning, monitoring, CI/CD, etc.).\n• Build & maintain data pipelines and model performance for scalability and maintainability.\n• Ensure all models adhere to organizational AI policies, responsible AI practices, and audit requirements.\n• Support data exploration, feature engineering, and occasional model building where needed.\n• Automate model retraining, testing, and monitoring to ensure performance over time.\n• Document ML workflows, governance checkpoints, and risk assessments.\n• Partner with CloudOps,DevOps, IT, and security teams to integrate solutions into enterprise platforms.\n\nThe position requires autonomy and reliability in performing duties while maintaining close communication with rest of stake-holders.\n\nQualifications and Profile\n• Have bachelor's or master’s degree in the field of AI / ML and data science with proven ability to design and develop models\n• 8+ years of experience in software development, data science and ML, with at least 3+ years in AI engineering roles.\n• Proven experience in end-to-end ML lifecycle: data wrangling, model development, deployment, and monitoring.\n• Strong programming skills in Python with Solid knowledge of AI/ML, including LLMs and data science libraries like pandas, scikit-learn, TensorFlow/PyTorch, etc.\n• Experience with LLM Orchestration frameworks like Langchain, LangGraph, vLLM, LMDeploy.\n• Strong knowledge in NoSQL databases (any experience in Graph database is desirable)\n• Experience with MLOps tools: MLflow, Airflow, Kubeflow, or similar.\n• Familiarity with either of cloud platforms (GCP, AWS) for AI Solutioning and ML deployment.\n• Knowledge of data science techniques including supervised/unsupervised learning, NLP, time series, etc.\n• Experience with CI/CD pipelines and containerization (Docker, Kubernetes).\n• Strong understanding of AI governance, model risk management, and regulatory requirements in AI.\n• Ability to communicate technical concepts to non-technical stakeholders.\n\nPreferred skills:\n• Experience with Responsible AI frameworks and bias/fairness testing.\n• Exposure to feature stores, model registries, and data versioning.\n• Knowledge of data privacy, anonymization, and compliance in regulated industries (e.g., banking, healthcare).",
  'apply_options': [{'title': 'LinkedIn Singapore',
    'link': 'https://sg.linkedin.com/jobs/view/senior-machine-learning-ai-engineer-at-cr%C3%A9dit-agricole-cib-4329742546?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'},
   {'title': 'BeBee SG',
    'link': 'https://sg.bebee.com/job/426d4e491fa3ccb8ff5781b11cb456a3?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}],
  'job_id': 'eyJqb2JfdGl0bGUiOiJTZW5pb3IgTWFjaGluZSBMZWFybmluZy9BSSBFbmdpbmVlciIsImNvbXBhbnlfbmFtZSI6IkNyw6lkaXQgQWdyaWNvbGUgQ0lCIiwiYWRkcmVzc19jaXR5IjoiU2luZ2Fwb3JlIiwiaHRpZG9jaWQiOiJtTWdGM1hEMjkySXREUDJOQUFBQUFBPT0iLCJ1dWxlIjoidytDQUlRSUNJSlUybHVaMkZ3YjNKbCIsImhsIjoiZW4ifQ=='},
 {'title': 'Applied AI, Forward Deployed Machine Learning Engineer- Singapore',
  'company_name': 'Mistral AI',
  'location': 'Singapore',
  'via': 'Lever',
  'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Machine+Learning+Engineer&htidocid=xut7DZ20o1OOb_ZUAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_0WOvQoCMRCEsb0XEKy2Fu8igo1WB_6geJWN3ZHLLUkk7oZsQH0rH9FY2Qx8w8A31WdS3doYg8cR2tMCDpyeOo2wwxj4XcpOG-cJ4YI6kScLe7KFMdVwLagjJ4QazjyAlIlxwARHZhtwtnU5R9koJRIaK1lnbxrDD8WEA7_UnQf5RS9OpyLUGfvVevlqItn5tPOSkw7lFnj6y75Ol3qyswAAAA&shmds=v1_AdeF8KgfYGe7hpWdiGgIjV-I7mpCTEXQOi6wRSI1BmnFT3ZJkA&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Machine+Learning+Engineer&htidocid=xut7DZ20o1OOb_ZUAAAAAA%3D%3D',
  'thumbnail': 'https://serpapi.com/searches/695a63987d6e700c1afa5109/images/30df5819a7c86381536644073239ddf001162acf14a27d2ae908369c62bc4654.png',
  'extensions': ['Full-time'],
  'detected_extensions': {'schedule_type': 'Full-time'},

In [10]:
for job in jobs_results:
    print(job)

{'title': 'Principal Machine Learning System Engineer', 'company_name': 'Atlassian', 'location': 'Singapore', 'via': 'Join Our Talent Community | Atlassian Careers Apply - Atlassian', 'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Machine+Learning+Engineer&htidocid=hmrzybxb-pIZD7iaAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xWNMQrCQBAAsc0DLKy2FsyJYKNViiCIgpAHhM2x3K1cdo_bK-JPfK6xmWKmmOa7abpXYfGcMcETfWQheBAWYQkwfKzSDL2EVVOBA9x1Aluzj6ACN9WQaHeNtWa7OGeW2mAVK_vW6-xUaNLFvXWyP0aLWCgnrDSezselzRL2264mNGMUYIFh3WLWQj8wJe5lmwAAAA&shmds=v1_AdeF8KgrPu3QG_JOgGfeSmSElJhhiLI16JeRz-fSgfPRagzIvw&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Machine+Learning+Engineer&htidocid=hmrzybxb-pIZD7iaAAAAAA%3D%3D', 'extensions': ['Full-time'], 'detected_extensions': {'schedule_type': 'Full-time'}, 'description': 'Overview\n\nWorking at Atlassian\n\nAtlassians can choose where they work – whether in an office, from home, or a combination of the two. That way, Atlassians have more control over supporting their family, personal goals, and other priorities. We can hire people in any country where we have a legal entity. Interviews and onboarding are conducted virtually, a part of being a distributed-first company.\n\nResponsibilities\n\nAbout Atlassian\n\nAtlassian\'s mission, "to unleash the potential of every team," serves as the foundation of everything we do. We have developed well-known collaborative products, such as Jira, Confluence, and Bitbucket, that fit into the fabric of teamwork across different types of teams and the processes to help every team succeed.\n\nAtlassian helps teams everywhere change the world. Our products power revolutions across many industries, enabling teams to collaborate effectively and achieve their highest potential. Take, for example, NASA launching the Rover on Mars or Cochlear gifting those born deaf with the ability to hear. Your work directly impacts the products they use to promote humanity.\nAbout Central AI Org\n\nOur organization is dedicated to driving AI innovation across all Atlassian products and platforms. We aim to deliver seamless AI experiences while establishing a robust Atlassian AI infrastructure for the future. Our purpose is to:\n• Develop horizontal AI capabilities and infrastructure that can be leveraged across all products.\n• Establish a centralized Search, Q&A, and Conversational AI system that integrates seamlessly with all Atlassian products.\n• Explore the integration of Atlassian products with AI solutions beyond the Atlassian ecosystem.\n\nAbout AI & ML Platform Team\n\nOur team’s goal is to build the foundations to democratize AI and Machine Learning for Atlassian’s teams, customers, and ecosystem. We aim to build productive and reliable tools that empower Atlassian teams to harness the power of AI. These tools will facilitate the development, deployment, measurement, and operation of AI & ML experiences.\n\nOur tools are designed to integrate seamlessly with other Atlassian platforms, including the Atlassian Data Platform. This integration enables teams to efficiently and swiftly incorporate AI and ML capabilities into their workflows while strictly adhering to all security and data usage policies. Our primary goal is to deliver a smooth and hassle-free experience for Atlassian users, empowering them to harness the potential of AI and ML without any complications.\nAbout This Role\n\nAs a Principal Machine Learning System Engineer on the AI & ML Platform team, you will play a pivotal role in developing and refining the core infrastructure that empowers all Atlassian software engineers, ML engineers, and data scientists to create, train, evaluate, deploy, and manage Machine Learning models and pipelines.\n\nYou will collaborate closely with product teams, such as Jira and Confluence, to solve their specific challenges in building ML solutions. This may involve curating high-quality ML datasets, fine-tuning open-sourced Large Language Models (LLMs), or accessing proprietary LLMs. Your expertise in both ML and software development expertise will be instrumental in overcoming challenging problems and navigating complex infrastructure and architectural issues.\n\nThis position offers you the chance to lead projects from the technical design phase all the way to launch. You will partner with various teams and internal stakeholders to achieve impactful results.\n\nIn this role, you\'ll get the chance to:\n• Collaborate with your teammates to solve complex problems, from technical design to launch.\n• Deliver cutting-edge solutions that are used by other Atlassian teams and products to build AI features that reach millions of customers.\n• Deliver code reviews, documentation & bug fixes within a strong engineering culture\n• Partner across engineering teams to take on company-wide initiatives spanning multiple projects.\n• Mentor junior members of the team.\n\nOn your first day, we’ll expect you to have\n• Extensive experience in building Machine Learning and AI infra/platform/system (generally 5+ years)\n• Comprehensive ML lifecycle expertise: proven experience developing, deploying, and maintaining end-to-end ML systems, from data engineering to model serving and monitoring.\n• Large-scale system design: Extensive experience designing and building scalable, fault-tolerant, and high-performance distributed systems for machine learning.\n• Proficiency with frameworks and languages: Expert-level proficiency in Python and ML frameworks like PyTorch, TensorFlow, or JAX. Familiarity with other languages like Go, Java, or Scala is also beneficial.\n• MLOps and automation: Deep experience implementing MLOps, CI/CD pipelines, and automation for continuous training, deployment, and monitoring of ML models.\n\nIt would be great, but not required if you have\n• Cloud infrastructure: Hands-on expertise with major cloud platforms such as AWS, GCP, or Azure, including their specific AI/ML services and compute resources like GPUs.\n• Big data processing: Experience with distributed computing frameworks for large-scale data processing, such as Spark, Ray, or Dask.\n• Performance optimization: A demonstrated ability to diagnose and solve complex performance and optimization problems for ML models and infrastructure.\n• Generative AI systems: Experience with GenAI frameworks and tools, including developing and fine-tuning large language models (LLMs) and building retrieval-augmented generation (RAG) systems.\n\nQualifications\n\nBenefits & Perks\n\nAtlassian offers a wide range of perks and benefits designed to support you, your family and to help you engage with your local community. Our offerings include health and wellbeing resources, paid volunteer days, and so much more. To learn more, visit go.atlassian.com/perksandbenefits.\n\nAbout Atlassian\n\nAt Atlassian, we\'re motivated by a common goal: to unleash the potential of every team. Our software products help teams all over the planet and our solutions are designed for all types of work. Team collaboration through our tools makes what may be impossible alone, possible together.\n\nWe believe that the unique contributions of all Atlassians create our success. To ensure that our products and culture continue to incorporate everyone\'s perspectives and experience, we never discriminate based on race, religion, national origin, gender identity or expression, sexual orientation, age, or marital, veteran, or disability status. All your information will be kept confidential according to EEO guidelines.\n\nTo provide you the best experience, we can support with accommodations or adjustments at any stage of the recruitment process. Simply inform our Recruitment team during your conversation with them.\n\nTo learn more about our culture and hiring process, visit go.atlassian.com/crh.', 'apply_options': [{'title': 'Join Our Talent Community | Atlassian Careers Apply - Atlassian', 'link': 'https://join.atlassian.com/jobs/22598?lang=en-us&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'Indeed', 'link': 'https://sg.indeed.com/viewjob?jk=283c61f4ef488c39&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'Glassdoor', 'link': 'https://www.glassdoor.sg/job-listing/principal-machine-learning-system-engineer-atlassian-JV_IC3235921_KO0,42_KE43,52.htm?jl=1009893404749&utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'Built In', 'link': 'https://builtin.com/job/principal-machine-learning-system-engineer/7284978?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'Built In Singapore', 'link': 'https://builtinsingapore.com/job/principal-machine-learning-system-engineer/7284978?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'Bayt.com', 'link': 'https://www.bayt.com/en/singapore/jobs/principal-machine-learning-system-engineer-73802853/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'Atlassian Jobs: View Listings For Open Positions - ICIMS', 'link': 'https://globalcareers-atlassian.icims.com/jobs/22597/principal-machine-learning-system-engineer/job?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'BeBee SG', 'link': 'https://sg.bebee.com/job/8957231a7508315a1e6a87d5a965aac2?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}], 'job_id': 'eyJqb2JfdGl0bGUiOiJQcmluY2lwYWwgTWFjaGluZSBMZWFybmluZyBTeXN0ZW0gRW5naW5lZXIiLCJjb21wYW55X25hbWUiOiJBdGxhc3NpYW4iLCJhZGRyZXNzX2NpdHkiOiJTaW5nYXBvcmUiLCJodGlkb2NpZCI6Imhtcnp5YnhiLXBJWkQ3aWFBQUFBQUE9PSIsInV1bGUiOiJ3K0NBSVFJQ0lKVTJsdVoyRndiM0psIiwiaGwiOiJlbiJ9'}
{'title': 'Senior Machine Learning/AI Engineer', 'company_name': 'Crédit Agricole CIB', 'location': 'Singapore', 'via': 'LinkedIn Singapore', 'share_link': 'https://www.google.com/search?ibp=htl;jobs&q=Machine+Learning+Engineer&htidocid=mMgF3XD292ItDP2NAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xWNsQ3CMBAARZsRqJ4WiRgh0YQKIoSCoMoAkWNetpH5t_5dZBgWYA4WIzRX3BVXvRdV0yNFFrhbFyIh3NAKRfLm2MGZ_KxQYANXHkHn5AIwwYXZJ1weQilZG2NUU-212BJd7fhlmHDkyTx51D8GDVYwJ1tw2O23U53Jr1etfD-PWODoJTpOCG13gkjQz3ebWfAHHWh14J8AAAA&shmds=v1_AdeF8KilK3BlsmwXKCpWq-Is-xY_-2cMmnuMDXYlg1iEbgfGRA&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=Machine+Learning+Engineer&htidocid=mMgF3XD292ItDP2NAAAAAA%3D%3D', 'thumbnail': 'https://serpapi.com/searches/695a63987d6e700c1afa5109/images/30df5819a7c8638190ee171e28217b897639f7c8f9f48f3fdbe08871a090518a.jpeg', 'extensions': ['5 days ago', 'Full-time'], 'detected_extensions': {'posted_at': '5 days ago', 'schedule_type': 'Full-time'}, 'description': "Who we are\n\nCrédit Agricole Corporate and Investment Banking (Crédit Agricole CIB) is the corporate and investment banking arm of Crédit Agricole Group, world’s 10th largest bank by total assets.\n\nOur Singapore center is the 2nd largest IT setup (after Paris Head Office) for Crédit Agricole CIB's worldwide business. We work daily with international branches located in 30 markets by:\n• Envisioning and preparing the Bank’s futures information systems\n• Partnering and supporting core banking flagships and transverse areas in their large scale development projects\n• Providing premium In-house Banking applications\n\nThis unique positioning empowers us to bring our core banking business a sustainable competitive advantage on the market.\n\nWe seek innovative and agile people sharing our mindset to support ambitious and forthcoming technological challenges.\n\nPosition\n\nIn a challenging and multicultural environment, we are looking for a Senior Machine Learning/AI Engineer to join our Digital Excellence Centre (DEC) department of Crédit Agricole CIB. The department handles the development of transversal and international projects.\n\nWe are looking for a Builder-type AI Engineer with a strong background in Traditional ML and GenAI (LLM,Agentic), who can design, build, and deploy end-to-end machine learning solutions. This hybrid role requires a hands-on expert who can not only build models when needed but also engineer scalable, production-grade ML systems while adhering to the organization's AI governance and compliance standards.\n\nMain responsibilities\n• As a Senior AI Engineer, you’ll be part of growing engineering team and help to build the next generation AI Solutions.\n• Collaborate with business stakeholders to understand use cases and define AI solution; work on Proof of Concepts wherever needed\n• Engineer and deploy ML models into production using MLOps best practices (model versioning, monitoring, CI/CD, etc.).\n• Build & maintain data pipelines and model performance for scalability and maintainability.\n• Ensure all models adhere to organizational AI policies, responsible AI practices, and audit requirements.\n• Support data exploration, feature engineering, and occasional model building where needed.\n• Automate model retraining, testing, and monitoring to ensure performance over time.\n• Document ML workflows, governance checkpoints, and risk assessments.\n• Partner with CloudOps,DevOps, IT, and security teams to integrate solutions into enterprise platforms.\n\nThe position requires autonomy and reliability in performing duties while maintaining close communication with rest of stake-holders.\n\nQualifications and Profile\n• Have bachelor's or master’s degree in the field of AI / ML and data science with proven ability to design and develop models\n• 8+ years of experience in software development, data science and ML, with at least 3+ years in AI engineering roles.\n• Proven experience in end-to-end ML lifecycle: data wrangling, model development, deployment, and monitoring.\n• Strong programming skills in Python with Solid knowledge of AI/ML, including LLMs and data science libraries like pandas, scikit-learn, TensorFlow/PyTorch, etc.\n• Experience with LLM Orchestration frameworks like Langchain, LangGraph, vLLM, LMDeploy.\n• Strong knowledge in NoSQL databases (any experience in Graph database is desirable)\n• Experience with MLOps tools: MLflow, Airflow, Kubeflow, or similar.\n• Familiarity with either of cloud platforms (GCP, AWS) for AI Solutioning and ML deployment.\n• Knowledge of data science techniques including supervised/unsupervised learning, NLP, time series, etc.\n• Experience with CI/CD pipelines and containerization (Docker, Kubernetes).\n• Strong understanding of AI governance, model risk management, and regulatory requirements in AI.\n• Ability to communicate technical concepts to non-technical stakeholders.\n\nPreferred skills:\n• Experience with Responsible AI frameworks and bias/fairness testing.\n• Exposure to feature stores, model registries, and data versioning.\n• Knowledge of data privacy, anonymization, and compliance in regulated industries (e.g., banking, healthcare).", 'apply_options': [{'title': 'LinkedIn Singapore', 'link': 'https://sg.linkedin.com/jobs/view/senior-machine-learning-ai-engineer-at-cr%C3%A9dit-agricole-cib-4329742546?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}, {'title': 'BeBee SG', 'link': 'https://sg.bebee.com/job/426d4e491fa3ccb8ff5781b11cb456a3?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic'}], 'job_id': 'eyJqb2JfdGl0bGUiOiJTZW5pb3IgTWFjaGluZSBMZWFybmluZy9BSSBFbmdpbmVlciIsImNvbXBhbnlfbmFtZSI6IkNyw6lkaXQgQWdyaWNvbGUgQ0lCIiwiYWRkcmVzc19jaXR5IjoiU2luZ2Fwb3JlIiwiaHRpZG9jaWQiOiJtTWdGM1hEMjkySXREUDJOQUFBQUFBPT0iLCJ1dWxlIjoidytDQUlRSUNJSlUybHVaMkZ3YjNKbCIsImhsIjoiZW4ifQ=='}

In [17]:
import pandas as pd
import serpapi
from dotenv import load_dotenv
import os
from openai import OpenAI

load_dotenv()
SERPAPI_API_KEY = os.getenv('SERPAPI_API_KEY') 

client = OpenAI()

def get_refined_search_query(user_query: str):
    system_prompt = """
    You are an expert in extracting interpreting the preferred job position/role based on user input.
    Only output a clear job position to be used for Google search.
    """

    response = client.responses.create(
        model='gpt-5-nano',
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_query}
        ]
    )

    search_query = response.output_text
    return search_query

def scrape_google_jobs(query: str):
    refined_query = get_refined_search_query(query)
    print(f'Searching for: {refined_query}')
    search_params = {
        "engine": "google_jobs",
        "q": refined_query,
        "hl": "en",
        "location": "Singapore",
        "api_key": SERPAPI_API_KEY
    }

    results = serpapi.search(**search_params)
    jobs_results = results.get('jobs_results')

    clean_jobs = []
    for job in jobs_results:
        clean_job = JobResult(
            title=job['title'],
            company=job['company_name'],
            location=job['location'],
            link=job['share_link'],
            description=job['description'],
            salary=job['detected_extensions'].get('salary'),
            posted_at=job['detected_extensions'].get('posted_at')
        )
        clean_jobs.append(clean_job)

    return clean_jobs

In [20]:
query = 'find me ai engineer internships in singapore'
jobs = scrape_google_jobs(query)
jobs

Searching for: AI Engineer Internship in Singapore

[JobResult(title='Building AI Engineer Intern', company='Schneider Electric', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internship+in+Singapore&htidocid=DadXvTo8Iylc87d0AAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXOsQrCMBCAYVz7CC7eLNhIwUUnhSJ17QOUND2Sk3gXcif0OXxidfnX728-m6a7vSkvxBGuA_QciRErDGxYGQ7wkBkUfQ0JhOEuEjNuL8ms6Nk51dxGNW8U2iAvJ4yzrO4ps_4zafIVS_aGU3c6rm3huN-NITHS8lP6jMEqBSCG8bfgi1T8AuL8N8-VAAAA&shmds=v1_AdeF8Khlw07axfQQpC8EWTfqI-yWEDllsvp5ODrBTFzCxC1mkg&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internship+in+Singapore&htidocid=DadXvTo8Iylc87d0AAAAAA%3D%3D', description="In Schneider Electric, everything we do is geared towards advancing progress and sustainability for all—our colleagues, customers, partners, and the communities and societies we serve.\n\nWhether it's through our products, software, and services that propel the digital transformation of energy management and automation, or through our corporate citizenship and volunteer activities, we make a meaningful impact by empowering people and organizations to become more resilient, electric, and digital.\n\nWhich is where you come in. Working at Schneider Electric means working toward a cleaner, better world. You are part of a global team built on inclusion, mastery, purpose, action, curiosity, and teamwork, turning sustainability ambitions into actions.\n\nWe are now hiring interns for our H1 2026 cohort! Internships will start in 2 batches: January 2026 or February 2026. Please indicate your exact availability in your application. Students who can commit full-time will be preferred.\n\nJoin us as an Building AI Engineer Intern to make an impact!\n\nLocation: Kallang\n\nThe Role:\n\nWhat will you do?\n• Design, develop, and deploy AI models for predictive maintenance, energy optimization, occupancy analytics, and fault detection in building systems\n• Work with BMS, EMS, IoT sensors, and other building data sources to collect, clean, and structure data for AI applications\n• Collaborate with software engineers and solution architects to integrate AI models into scalable platforms and edge devices\n• Stay ahead of industry trends and emerging technologies in AI, smart buildings, and energy management\n• Prototype new solutions and validate them through pilot projects\n• Work closely with internal teams, clients, and partners to understand requirements, present solutions, and ensure successful implementation\n• Ensure AI solutions comply with data privacy regulations, cybersecurity standards, and ethical AI practices\n\nWhat qualifications will make you successful?\n• Bachelor’s or Master’s degree in Computer Science, Electrical Engineering, Data Science, or related fields\n\nSkills/Systems knowledge:\n• 2 years of experience in AI/ML development, preferably in building automation, energy systems, or smart infrastructure\n• Proficiency in Python, TensorFlow/PyTorch, and data engineering tools\n• Familiarity with building systems (HVAC, lighting, access control), BMS/EMS platforms, and IoT protocols\n• Experience with cloud platforms (Azure, AWS, GCP) and edge computing\n• Strong analytical, problem-solving, and communication skills\n\nWhat’s in it for me?\n• Global Family Leave\n• Comprehensive medical coverage for employee and dependents\n• Worldwide Employee Stock Ownership\n• Hybrid work arrangement (New Ways of Working)\n• …and more!\n\nLooking to make an IMPACT with your career?\n\nWhen you are thinking about joining a new team, culture matters. At Schneider Electric, our values and behaviors are the foundation for creating a great culture to support business success. We believe that our IMPACT values – Inclusion, Mastery, Purpose, Action, Curiosity, Teamwork – starts with us.\n\nIMPACT is also your invitation to join Schneider Electric where you can contribute to turning sustainability ambition into actions, no matter what role you play. It is a call to connect your career with the ambition of achieving a more resilient, efficient, and sustainable world.\n\nWe are looking for IMPACT Makers; exceptional people who turn sustainability ambitions into actions at the intersection of automation, electrification, and digitization. We celebrate IMPACT Makers and believe everyone has the potential to be one.\n\nBecome an IMPACT Maker with Schneider Electric – apply today!\n\n€36 billion global revenue\n+13% organic growth\n150 000+ employees in 100+ countries\n#1 on the Global 100 World’s most sustainable corporations\n\nYou must submit an online application to be considered for any position with us. This position will be posted until filled.\n\nSchneider Electric aspires to be the most inclusive and caring company in the world, by providing equitable opportunities to everyone, everywhere, and ensuring all employees feel uniquely valued and safe to contribute their best. We mirror the diversity of the communities in which we operate, and ‘inclusion’ is one of our core values. We believe our differences make us stronger as a company and as individuals and we are committed to championing inclusivity in everything we do.\n\nAt Schneider Electric, we uphold the highest standards of ethics and compliance, and we believe that trust is a foundational value. Our Trust Charter is our Code of Conduct and demonstrates our commitment to ethics, safety, sustainability, quality and cybersecurity, underpinning every aspect of our business and our willingness to behave and respond respectfully and in good faith to all our stakeholders. You can find out more about our Trust Charter here\n\nSchneider Electric is an Equal Opportunity Employer. It is our policy to provide equal employment and advancement opportunities in the areas of recruiting, hiring, training, transferring, and promoting all qualified individuals regardless of race, religion, color, gender, disability, national origin, ancestry, age, military status, sexual orientation, marital status, or any other legally protected characteristic or conduct.", salary=None, posted_at=None),
 JobResult(title='AI Engineer Intern', company='Singtel Group', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internship+in+Singapore&htidocid=GIPB2X16kK4je5IQAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXIsQrCMBAAUFz7CZ1uVTARwUUnByl19QNKEo4kEu_C3Qn9AD9curzhDb_dsL_P8KBcCVFgJkMhOMKTIygGSQWYYGLODcdbMet69V61uawWrCaX-OOZMPLq3xx1Y9ESBHsLhsv5clpdp3wYX5WyYYNJ-NuhEmwROgv-AU_HkPaHAAAA&shmds=v1_AdeF8KiqNfJMV8ntSGz7IKWYMoBSIVOpcyFZRl3McJmZosfZiA&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internship+in+Singapore&htidocid=GIPB2X16kK4je5IQAAAAAA%3D%3D', description='Powering the Future with AIDA\n\nTo lead the next phase of our AI evolution, we’ve launched a new business unit AIDA – Artificial Intelligence & Data Analytics – a strategic engine driving our transformation designed to scale our AI ambitions with precision and purpose. This marks a pivotal shift in how we operate, innovate, and serve to embed intelligence into every layer of our business.\n\nAt Singtel, this is more than a technology upgrade. It’s a strategic transformation that redefines how value is created across the enterprise core— augmenting human capabilities and unlocking entirely new potential. It is a transformation journey by aligning people, platforms, and processes under one cohesive strategy. Our mission is to build AI literacy, and foster a culture where intelligence empowers people.\n\nWe welcome you to join us on a transformational journey that’s reshaping the telecommunications industry — and redefining what’s possible with AI at its core. Grow with us in a workplace that champions innovation, embraces agility, and puts human potential at the heart of everything we do.\n\nBe a Part of Something BIG!\n\nThe AI Engineer Intern will support the development, testing, and experimentation of next-generation AI solutions within AIDA, including Singtel’s pioneering AI innovations. The intern will engage in hands-on prototyping (“vibe coding”), explore new AI/GenAI tools, and assist engineers in building lightweight workflows, models, and applications.\n\nThis role offers a unique opportunity to gain practical exposure to AI engineering, rapid experimentation, and enterprise AI product development while contributing to real initiatives that shape how employees interact with AI across Singtel.\n\nMake an Impact by:\n• Support the development and prototyping of new AI and GenAI concepts, including early versions of the AI Avatar and related features.\n• Explore, evaluate, and experiment with AI tools, libraries, frameworks, and agentic AI capabilities to test feasibility and potential value.\n• Assist AI engineers with data preparation, prompt experimentation, model testing, and integration validation.\n• Act as an early-stage tester for new AI solutions to identify bugs, usability issues, and improvement opportunities.\n• Contribute to building lightweight scripts, workflows, or applications to demonstrate concepts and accelerate iteration.\n• Document findings, experiment results, and technical learnings to support engineering refinement and decision-making.\n• Collaborate with solution architects and AI engineers to understand requirements and contribute to iterative development.\n\nSkills for Success:\n• Bachelor’s or Master’s degree in Computer Science, Engineering, Data, AI/ML or related field.Master’s degree in AI, Tech Management, or Business Analytics.\n• Undergraduate degree in progress (Computer Science, Engineering, AI/ML, Data Science, or related fields). Prior internship or project experience in AI, GenAI, or software development.\n• Basic Python programming skills.\n• Familiarity with notebooks, APIs, or ML libraries.\n• Understanding of prompt engineering basics.\n• Ability to explore and test AI tools and frameworks. Exposure to LangChain/LangGraph or agentic AI tools.\n• Experience building lightweight apps or scripts.\n• Knowledge of cloud or container tools.\n• Curious, proactive learner with strong analytical thinking.\n• Comfortable with hands-on experimentation and rapid iteration.\n• Good communication and documentation habits.\n• Collaborative mindset when working with engineers. Interest in user experience or product thinking.\n\nAre you ready to say hello to BIG Possibilities?\n\nTake the leap with Singtel to unlock new opportunities and accelerate your growth. Apply now and start your empowering career!', salary=None, posted_at='19 days ago'),
 JobResult(title='Machine Learning and Generative AI Intern', company='Seagate Technology', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internship+in+Singapore&htidocid=eyVOYFyVHmLSEHIRAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xWOMQoCMRBFsd0j2Di14EYEG220Wla0WvtlNg5JJM6ETJD1Nh7V2Pzi8R785rtoTje0PjDBlTBzYAfID-iIKWMJb4JzDz0XygwbuMgEWj3rQRg6ERdpefSlJD0Yoxpbp6VmtrXyMsI0yWyeMul_RvWYKUUsNO7227lN7NargdBVAneyniWK-0BgGOoRTJLpBxh5skqjAAAA&shmds=v1_AdeF8KjzTyMoA5hfChV92NtHfZ9otNKmbkLeNirzV6ZnJLSUkg&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internship+in+Singapore&htidocid=eyVOYFyVHmLSEHIRAAAAAA%3D%3D', description="About our group:\n\nWe are the Global Factory Information Technologies (GFIT) team at Seagate. Our mission is to drive digital transformation across Seagate’s global manufacturing operations. We develop and implement data-driven solutions that enable real-time decision-making, predictive analytics, and intelligent automation.\n\nIn 2026, we are expanding our focus to include Generative AI (GenAI) as a core enabler of smart factory innovation. This includes using GenAI to enhance process optimization, automate knowledge generation, and create intelligent digital assistants that support factory operations.\n\nAbout the role - you will:\n\nAs an AI Intern specializing in Generative AI, you will collaborate with our Data Scientists and Engineers to explore and develop innovative GenAI applications for smart manufacturing. Your responsibilities may include:\n• Designing and prototyping GenAI models for factory use cases.\n• Developing AI-powered tools for automated report generation, anomaly explanation, and digital twin simulations.\n• Integrating GenAI solutions with factory control systems..\n\nThis is a high-impact role where your work will contribute to Seagate’s next-generation smart factory capabilities.\n\nAbout you:\n\nWe are looking for candidates who are passionate about AI and excited to explore the frontiers of Generative AI in real-world industrial settings. You should be:\n• Curious, inventive, and eager to learn.\n• Comfortable working independently and collaboratively in a fast-paced environment.\n• Good at Python programming and familiar with GenAI frameworks\n• Knowledgeable in machine learning, deep learning, and natural language processing.\n• Bachelor or master's students in Computer science, computer engineering\n\nYour experience includes:\n\nLocation:\n\nLocation: Woodlands, Singapore, W3\n\nTravel: None", salary=None, posted_at='15 days ago'),
 JobResult(title='AI Engineering Intern', company='Urban Redevelopment Authority', location='Singapore', link='https://www.google.com/search?ibp=htl;jobs&q=AI+Engineer+Internship+in+Singapore&htidocid=EmeBOT7JCamuGYIQAAAAAA%3D%3D&hl=en-US&shndl=37&shmd=H4sIAAAAAAAA_xXOsQrCMBAAUFz7CU43F01EcNGpg0gdFeeS1COJpHfhckr9En9XXd78ms-iWXU9HCkkQpREAXpSFII1nNlDRSdjBCY4MYeMy0NULXVvba3ZhKpO02hGniwTep7tg339M9ToBEt2isN2t5lNodC2N_GO4IJ3fGHmMiEpdE-NLEnfkAiuv4ErLPgFM7qJMpoAAAA&shmds=v1_AdeF8Kiic-2-6ojwqGlmPYHCpUcvasBItCa8rq78hgxhLn0A8w&source=sh/x/job/li/m1/1#fpstate=tldetail&htivrt=jobs&htiq=AI+Engineer+Internship+in+Singapore&htidocid=EmeBOT7JCamuGYIQAAAAAA%3D%3D', description="What the role is:\nURA has undergone a digitalisation journey to harness urban science, geospatial and data analytics, modelling and simulation, and AI technologies in urban planning and design. Our teams, with capabilities in data policy, governance, strategy, and engineering, product strategy, business analysis, software engineering, cloud engineering, urban design technologies, data science, AI/ML, and modelling and simulation, collaborate with planners, architects, and policymakers to create insights and digital solutions for Singapore’s urban planning challenges. You will be joining the PLAN AI Team, building Artificial Intelligence (AI)-enabled planning system & processes. This is part of the National AI Strategy and the MND Science & Technology Plan, focusing on strengthening central support for AI, building WOG AI Capabilities, and establishing a Public Sector AI Governance Framework.\n\nWhat you will be working on:\nThe fast-paced developments in the space of AI presents exciting opportunities to harness this technology to enhance the way URA officers work. Intern(s) will undertake some of or a mix of the following tasks:\n\n• support development and production of AI/ML tools to enhance urban planning & design work (e.g. LLM-enabled assistants, AI image generator [model training + explore latest diffusion models] etc)\n• exploration of new AI/ML techniques such as Text2SQL, RAG2SQL, multi-agent AI systems (or others) etc.\n\nLearning Outcomes:\n• Gain practical experience in developing and implementing AI/ML/LLM-enabled prototypes and solutions within Gov/URA's context.\n• Cultivate problem-solving and innovative thinking skills, particularly in proposing solutions to address users' needs.\n• Collaborate with cross-functional teams to design and implement solutions that meet business requirements\n\nWhat we are looking for:\n• Internship Period: May - Aug 2026. Full-time internship preferred.\n• Students pursuing Computer Science/ Information Technology with interest in AI/ML & GenAI, Smart Cities, Design & Artificial Intelligence\n• Familiarity with RAG techniques. Experience with UX/UI design and design tools like Canva will be a bonus\n\nNote: To facilitate the hiring process, please state your availability, including specific start and end date in your resume or application form.\n\nWe regret to inform that only shortlisted candidates will be notified.\n\nKindly note the selection process for this role will commence in Jan 2026.\n\nAbout Urban Redevelopment Authority\nThe Urban Redevelopment Authority (URA) is Singapore's national land use planning authority. URA prepares long term strategic plans, as well as detailed local area plans, for physical development, and then co-ordinates and guides efforts to bring these plans to reality. Prudent land use planning has enabled Singapore to enjoy strong economic growth and social cohesion, and ensures that sufficient land is safeguarded to support continued economic progress and future development.", salary=None, posted_at=None),